### ISSUE TITLE
[RFC] Enhancing RuntimeHandler

### ISSUE THREAD

**Issue by mcastelino** [cri-o/cri-o#1991]
Kata recently added support for multiple isolation mechanisms. It would be ideal to expose them as different runtime classes backed by the the same runtime binary implementation.

A simple way to do so without impacting OCI or kubernetes it to enhance crio to support specifying configuration along with the runtime binary. 

Hence the crio.conf would look like

```
[crio.runtime.runtimes.kata]
runtime_path = "/usr/bin/kata-runtime"

[crio.runtime.runtimes.katafirecracker]
runtime_path = "/usr/bin/kata-runtime"
runtime_params = "--kata-config /etc/kata-runtime/firecracker.toml"
```

And the RuntimeHandler would need to be enhanced along the lines of

https://github.com/kubernetes-sigs/cri-o/blob/master/oci/oci.go#L125

```
   // config table.
   type RuntimeHandler struct {
   RuntimePath string `toml:"runtime_path"`
   RuntimeParams string `toml:"runtime_params"`
   }
```

Some more details and discussions: https://github.com/kata-containers/runtime/issues/1082

**Comment by mrunalp** [comment]
SGTM :+1:

**Comment by rhatdan** [comment]
Looks like thie PR was closed.  Closing.  Reopen if I am mistaken.

**Comment by sboeuf** [comment]
No I don't think this was ever tackled, but I'll let @mcastelino give some clarifications on this.

**Comment by haircommander** [comment]
it was requested this was reopened in slack

**Comment by gattytto** [comment]
@haircommander thank you very much, this is because kata-containers can be passed an argument to choose a different config file so it would be nice to have "runtime_params " as another option to add in crio.conf for [runtime.runtimes.runtimeName]

Also trying to start a gVisor container from tekton using the following runtime in crio.conf fails for the pods to be frozen in a state of "containercreating" and there's actually no container being created. But I think this part deserves a separate issue (because checking on https://gvisor.dev/docs/tutorials/cni/ I can see networking for gVisor pods won't be as trivial as for kata-containers pods). 
````yaml
[crio.runtime.runtimes.runsc]
runtime_path = "/usr/local/bin/runsc"
````

**Comment by gattytto** [comment]
as a workaround, this can be archieved by using bash commandline wrappers to the real commands, like calling runsc-wrapper instead of runsc and add/edit arguments then actually pass them to runsc.

But this also means conmon calls made by cri-o are set strictly from code:
https://github.com/cri-o/cri-o/blob/85dee7dffe0a1f3e96ec8155c305deaaa4e7c74e/internal/oci/runtime_oci.go#L93

this code makes assumptions like I want logs in syslog(journalctl -f) and gives no chance in the crio.conf to override those arguments.

as mentioned above this can be overcome using bash script to patch the args in the way to the runtime binaries but it can be messy to "replace" values like for instance the logging settings

**Comment by rodrigc** [comment]
Based on this post https://kubernetes.slack.com/archives/CAZH62UR1/p1594242519386900 , I was encouraged by @haircommander to take a look at this.  I will take a look and see how far I get.

**Comment by sfxworks** [comment]
Being able to have gvisor run in kvm mode would be very nice.

**Comment by haircommander** [comment]
@rodrigc any progress here? if not, @sfxworks would you like to try to add support?
