### ISSUE TITLE
Add support for injecting init

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#2178]
If a container is not in the pod's pid namespace, the processes can get orphaned and signals can get missed. This is a tracker issue for allowing the user to inject an init binary (like: https://github.com/Yelp/dumb-init or https://github.com/krallin/tini) into any container that doesn't share the pod's pid namespace.

**Comment by giuseppe** [comment]
Podman by default we use catatonit when `--init` is specified

**Comment by mrunalp** [comment]
One requirement that we have here is making sure that the logs are streamed correctly so we get the logs from the container process spawned by the init. We want to avoid making changes to conmon. From what we discussed in last week's CRI-O meeting, https://github.com/Yelp/dumb-init supports that. Does `catatonit` also support that?

**Comment by giuseppe** [comment]
I guess so, it doesn't affect the std streams.  I forgot the reasons why we picked catatoinit and not considered dumb-init.  @vrothberg do you remember the details? :-)

**Comment by vrothberg** [comment]
[catatonit](https://github.com/openSUSE/catatonit) does a better job at signal handling than others. @cyphar is the author of catatonit and may add some details.

**Comment by vrothberg** [comment]
BTW, the init-logic from libpod can be found here: https://github.com/containers/libpod/blob/e7a2eecf5f3975edfb92cd2cacff0d34ef45f808/pkg/spec/createconfig.go#L153

**Comment by haircommander** [comment]
I am pretty sure runc now creates a pid 1 in a private pid namespace for a container. As such, I'm closing this

**Comment by PaulFurtado** [comment]
@haircommander do you have a pointer to where runc started doing that? I'm testing the static builds for cri-o 1.21 and neither runc nor crun appear do that.

cri-o is pretty unusable without that feature. That said, we do wrap the runc binary on our servers in order to inject additional settings into config.json, so we can easily workaround this, I'm just really surprised that this isn't a solved problem yet, so I'm wondering if I'm missing some setting somewhere or something. Thanks!

**Comment by haircommander** [comment]
so I am pretty sure I was wrong about that, and I can't remember why I was under that impression. That said, I don't think CRI-O can unconditionally inject an init in a private pid namespace--there are cases like a systemd container that would be broken if that was done. We could entertain having an allowed_annotation that allows a user to opt-into that behavior for certain pods, but that wouldn't be much different than a user specifying a different entrypoint (and adding the init binary into the image). In other words: I don't think we can do it automatically, so the current manual steps may be the best route

**Comment by PaulFurtado** [comment]
Yeah, crio likely should not do so blindly in an unconfigurable way since it would break cases where someone does in fact want to run an init process inside their docker container. I definitely understand that it would be a breaking change if crio just started doing this to all containers, but I was hoping it'd at least be an option at the crio level and make it possible for administrators to default that to on.

Under docker, you can specify `--init` at the docker daemon level to tell it to inject an init process into all docker containers that don't specifically opt out of it and I think many people do this. We run kubernetes internally as platform that many teams deploy into. Many different teams use many different images, there are several thousand images deployed. Many are based on internal base images and many are not. It'd be a huge amount of effort to get all of those entrypoints to be set to tini or catatonit, and harder to educate everyone on why they need to do this.

Comparatively, very few images I've seen in the wild actually need an init process in kubernetes since kubernetes and docker best practices have always been one-service-per-container. There definitely exist some popular images that do need to run systemd, such as freeipa and some others, but those are rare. So at least for us, injecting an init process into every container is a much better tradeoff.

On our end, I did end up solving this using our runc wrapper process to hook `runc create` and modify config.json inject catatonit so that we can maintain parity with docker, so I myself am now all set. However, I'd imagine that many other people would benefit from this feature. If we didn't have our runc wrapper solution, this would have been a significant blocker for us.

**Comment by haircommander** [comment]
another option is we could create an NRI daemon to do said injection cc @klihub :eyes: I would entertain a feature in CRI-O, though I am happy y'all found a workaround. let's see if more people want this feature, and if so, we can investigate the best route

**Comment by klihub** [comment]
> another option is we could create an NRI daemon to do said injection cc @klihub eyes I would entertain a feature in CRI-O, though I am happy y'all found a workaround. let's see if more people want this feature, and if so, we can investigate the best route

@haircommander I think that would be doable, although it would require an addition to NRI to allow changing `Process.Args`. We're conservative there and only pass it to the plugins as input, without allowing them to alter it. Also, I'm not sure... would such an init-injector plugin also need in some cases the image entrypoint in addition to `Process.Args` ?

**Comment by haircommander** [comment]
yeah I would guess the entrypoint would be needed too
