### ISSUE TITLE
Support pulling an image specified by both tag and digest

### ISSUE THREAD

**Issue by sfxworks** [cri-o/cri-o#2351]
**Description**

Hi all! Currently trying to get skaffold to work. Skaffold works by pulling an image specified by both tag and digest. I wanted to know if you could support this in crio?

https://github.com/GoogleContainerTools/skaffold/issues/2089#issuecomment-491000366
**Additional information you deem important (e.g. issue happens only occasionally):**

Example: 
```
root@a2:~# crictl pull gcr.io/allthingssfx/hook-to-k8s:v0.28.0-116-ga1172365-dirty@sha256:9154d56ca7364f5f3a005c469ab0e53ee005641beb70fcbbf6d014af1f19858b
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Invalid image name "gcr.io/allthingssfx/hook-to-k8s:v0.28.0-116-ga1172365-dirty@sha256:9154d56ca7364f5f3a005c469ab0e53ee005641beb70fcbbf6d014af1f19858b", unknown transport "gcr.io/allthingssfx/hook-to-k8s"
root@a2:~# crictl pull gcr.io/allthingssfx/hook-to-k8s:v0.28.0-116-ga1172365-dirty
Image is up to date for gcr.io/allthingssfx/hook-to-k8s@sha256:9154d56ca7364f5f3a005c469ab0e53ee005641beb70fcbbf6d014af1f19858b
```

**Output of `crio --version`:**

Currently using crio version 1.13 built from source ~ 2 months ago.A
```
root@a1:~# crio --version
crio version 1.13.1-dev
commit: ""

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical env

**Comment by saschagrunert** [comment]
Hey @sfxworks :wave:, thanks for reporting the issue!

> Skaffold works by pulling an image specified by both tag and digest. I wanted to know if you could support this in crio?

What would be the expected behavior when pulling via tag and digest? Should the tag be used to lookup the image whereas the overall pull fails if the remote manifests digest does not match the provided one? Or should the tag or digest simply be stripped from the pull?

For me this seems not clear and I would prefer in pulling either by tag or by digest. :man_shrugging: I think if this is really a wanted feature we could think about adding it to containers/image to have a consistent implementation for related projects.

cc @vrothberg

**Comment by sfxworks** [comment]
I always thought the digest was there to verify the image like an extra step in security, and the tag to select the image desired from the repo. I may be wrong though.

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mrunalp** [comment]
IIRC, in this case, the tag is ignored. I would let @mtrmac or @vrothberg comment on supporting it in containers/image.

**Comment by mtrmac** [comment]
> I always thought the digest was there to verify the image like an extra step in security, and the tag to select the image desired from the repo. I may be wrong though.

Sure, that can work, but it’s also a bit incoherent. If you, somehow, determine the expected digest value for the tag = for the image, and the image exists on the registry, does it _really_ matter that the tag differs? At least in the case of known-movable tags like `:latest` or `:`_majorVersion_, once something authoritative looks up the expected digest for _foo_`:latest`, why shouldn’t the cluster just go on deploying _foo_@`_expectedDigest_, _even if the `:latest` tag was moved to an even newer image in the meantime_?

Sure, in the case of expected-to-be-permanent tags that should never move, failing instead of continuing to use the image when the tag moves would alert someone that the tag has moved and it shouldn’t have… OTOH, even in that case, as long as the _expectedDigest_ value has been determined in a supposedly-secure/authoritative way, why should moving the tag cause an application outage?

---

Alternatively, it would be possible to interpret the input so that the tag is ignored, and only the digest matters… but in that case the tag can be anything, in particular it can be misleading.

---

(I’m quite sure there was a previous issue in one of the projects, in CRI-O I think, discussing the :tag@digest syntax support, but I can’t find it now.)

**Comment by mtrmac** [comment]
As far as implementation goes, right now c/image/docker explicitly rejects such input. It would be fairly easy to allow it (using one of the two semantics above); I’m more worried about all the higher-layer code (buildah/podman/CRI-O) that may be manually parsing the strings not being ready to handle such input.

**Comment by mtrmac** [comment]
> (I’m quite sure there was a previous issue in one of the projects, in CRI-O I think, discussing the :tag@digest syntax support, but I can’t find it now.)

https://github.com/containers/buildah/issues/1407

**Comment by sfxworks** [comment]
> why shouldn’t the cluster just go on deploying foo@expectedDigest, even if the :latest tag was moved to an even newer image in the meantime?

What argument would you give for scenarios where you are dealing with images containing variants of itself, like `ceph/daemon` and want to specifically verify and remember what image you're getting, like 
 `latest-nautilus`? So you would get the latest at the time, append the digest so it becomes `ceph/daemon:latest-nautilus@sha256XXXXXX`.  Coming back to a k8s manifest looking at the image tags, I'd be left with `ceph/daemon:sha256XXXXXX` making me wonder which variant exactly I'm getting. For this specific scenario, there's naming the manifest, but that's relying on k8s. Apps that are meant to be sidecar'd it could be a bit confusing without proper labeling or investigation. 

At the same time, I see your point and don't entirely have a good counter-argument for this. In skaffold's example, I guess it would be ensuring a malicious build (generated by a somehow unlikely but possible scenario where a registry was corrupted and injecting malicious code into new images) wasn't deployed in-cluster since it knows the digest given it managed the build process for it.  Can't say though. Docker Hub was just breached a bit though, so I do like that idea until I make an internal Harbor registry.

**Comment by mtrmac** [comment]
> > why shouldn’t the cluster just go on deploying foo@expectedDigest, even if the :latest tag was moved to an even newer image in the meantime?
> 
> What argument would you give for scenarios where you are dealing with images containing variants of itself, like `ceph/daemon` and want to specifically verify and remember what image you're getting, like
> `latest-nautilus`? So you would get the latest at the time, append the digest so it becomes `ceph/daemon:latest-nautilus@sha256XXXXXX`.

Basically, my intuition is to punt on solving this inside the reference[1], and let whatever system has determined/remembered the digest value to record the original tag and intent.  E.g. an annotation on a pod object is no worse than a tag inside the pull spec, and the software that resolves the tag into a digest reference can plausibly set either similarly easily. I do agree that this is, also, an awkward non-solution.

https://github.com/containers/buildah/issues/1407 suggested refusing :tag@digest in the `docker://` syntax, and accepting it in the heuristic non-transport syntax, including CRI-O pull specs; that’s a possible compromise to stop propagating this idea further, while increasing compatibility with Docker… but it would be even more code than just supporting the syntax in c/image/docker.

---

[1] See above — either the reference enforces the tag value, and there will be an outage when the `latest-nautilus` tag moves, or it ignores the tag value, which makes the tag value unreliable, more or less a comment with constrained syntax. Embedding ignored comments inside otherwise-important config values is conceptually pretty awkward.

**Comment by chanseokoh** [comment]
Because of this, I cannot install Tekton on Red Hat OpenShift:

```
$ curl https://storage.googleapis.com/tekton-releases/latest/release.yaml 2> /dev/null | grep image:
        image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.10.1@sha256:f4409692f43c4781d949847e661109c69c1a9acb8453cd1219b8341d642cb756
        image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.10.1@sha256:e0a277b69a742ff0e49767d11f9a1325fcea7fb8bbbf2572af9d49116cbb2385
```

```
  Normal   Scheduled  76s                default-scheduler            Successfully assigned tekton-pipelines/tekton-pipelines-controller-65459f5b4d-jpj7d to crc-k4zmd-master-0                               
  Normal   Pulling    30s (x3 over 68s)  kubelet, crc-k4zmd-master-0  Pulling image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.10.1@sha256:f4409692f43c4781d949847e661109c69c1a9ac
b8453cd1219b8341d642cb756"                                                                                                                                                                                    
  Warning  Failed     30s (x3 over 68s)  kubelet, crc-k4zmd-master-0  Failed to pull image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.10.1@sha256:f4409692f43c4781d949847e661109c6
9c1a9acb8453cd1219b8341d642cb756": rpc error: code = Unknown desc = Invalid image name "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.10.1@sha256:f4409692f43c4781d949847e661109c69c1a
9acb8453cd1219b8341d642cb756", unknown transport "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller"                                                                                         
  Warning  Failed     30s (x3 over 68s)  kubelet, crc-k4zmd-master-0  Error: ErrImagePull                                                                                                                     
  Normal   BackOff    2s (x5 over 67s)   kubelet, crc-k4zmd-master-0  Back-off pulling image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.10.1@sha256:f4409692f43c4781d949847e661109
c69c1a9acb8453cd1219b8341d642cb756"                                                                                                                                                                           
  Warning  Failed     2s (x5 over 67s)   kubelet, crc-k4zmd-master-0  Error: ImagePullBackOff                                                                                                                 
```

**Comment by maxandersen** [comment]
woohoo! thanks!
