### ISSUE TITLE
lazily load hostIP

### ISSUE THREAD

**Issue by cgwalters** [cri-o/cri-o#2478]
Today crio on *startup* tries to detect the primary host IP based on the default route.  AIUI this is simply so that address can be reported for `hostNetwork` pods.

The problem with this is that it creates a dependency on networking during startup which is racy.

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1713478
xref: https://github.com/cri-o/cri-o/pull/2102

Filing this specifically because this is impacting us for RHEL CoreOS doing basic host sanity testing in qemu; looks like we're getting an IPv6 address first before IPv4.

If we did this lazily then crio's startup wouldn't be dependent on networking.

**Comment by haircommander** [comment]
Unfortunately it seems it also be a fallback for the IP of the stream server. So we would either need to make sure a user configures a valid StreamAddress, or we can start after networking? WDYT @umohnani8 @mrunalp

**Comment by cgwalters** [comment]
> Unfortunately it seems it also be a fallback for the IP of the stream server.

Stream can listen on all interfaces right?

**Comment by cgwalters** [comment]
See also https://github.com/openshift/installer/pull/1768

**Comment by haircommander** [comment]
something worth note here: if dhcp takes a bit to figure out hostname, cri-o will mount the incorrect hostname in `/etc/hosts`. since these files are static upon container creation, the containers that come up before the network is fully initialized would have a wonky hostname.

Of course, this is something that should be figured out on the kube level, bc dhcp can change the hostname again later... I am not sure how we'd do that other than having the container's /etc/hosts be a hard link to the hosts, rather than a bind mount
