### ISSUE TITLE
Installing cri-o on Fedora 30 based on documentation fails

### ISSUE THREAD

**Issue by adelton** [cri-o/cri-o#2713]
**Description**

The page https://cri-o.io/ says

> Fedora: Available on all supported Fedora versions 28, 29 and Rawhide.
> `dnf install cri-o`

The page https://github.com/cri-o/cri-o/blob/master/README.md says

> Fedora, CentOS, RHEL, and related distributions: `sudo yum install crio`

However, on Fedora 30 and rawhide, module needs to be installed first, to be able to get `cri-o`.

**Steps to reproduce the issue:**
1. on Fedora 30, run `dnf install -y cri-o`

**Describe the results you received:**

```
Fedora Modular 30 - x86_64                      3.0 MB/s | 2.7 MB     00:00    
Fedora Modular 30 - x86_64 - Updates            3.6 MB/s | 2.4 MB     00:00    
Fedora 30 - x86_64 - Updates                     13 MB/s |  19 MB     00:01    
Fedora 30 - x86_64                               25 MB/s |  70 MB     00:02    
No match for argument: cri-o
Error: Unable to find a match: cri-o
```

**Describe the results you expected:**

```
Dependencies resolved.
================================================================================
 Package                     Arch   Version                Repository      Size
================================================================================
Installing:
 cri-o                       x86_64 2:1.13.0-1.gite8a2525.module_f30+3068+5f412e7f
                                                           fedora-modular  11 M
Installing dependencies:
 container-selinux           noarch 2:2.111.0-1.fc30       updates         48 k
 containernetworking-plugins x86_64 0.8.1-1.fc30           updates         19 M
 containers-common           x86_64 1:0.1.37-2.fc30        updates         48 k
 runc                        x86_64 2:1.0.0-93.dev.gitb9b6cc6.fc30
                                                           updates        2.5 M
 selinux-policy              noarch 3.14.3-43.fc30         updates        126 k
 selinux-policy-targeted     noarch 3.14.3-43.fc30         updates         14 M
 libbsd                      x86_64 0.9.1-3.fc30           fedora         100 k
 libnet                      x86_64 1.1.6-17.fc30          fedora          61 k
 libnl3                      x86_64 3.4.0-8.fc30           fedora         286 k
 libselinux-utils            x86_64 2.9-1.fc30             fedora         147 k
 policycoreutils             x86_64 2.9-1.fc30             fedora         193 k
 protobuf-c                  x86_64 1.3.1-2.fc30           fedora          33 k
 rpm-plugin-selinux          x86_64 4.14.2.1-4.fc30.1      fedora          24 k
Installing weak dependencies:
 criu                        x86_64 3.12-11.fc30           updates        476 k

Transaction Summary
================================================================================
Install  15 Packages

Total download size: 49 M
Installed size: 186 M
Is this ok [y/N]:
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The https://cri-o.io/ mentions Fedora 28 as supported but it was EOL'd, so it really shouldn't be listed as supported. On the other hand, Fedora 30 was released, so that one should have supported steps for installing CRI-O.

This was initially reported as https://bugzilla.redhat.com/show_bug.cgi?id=1710958 and the necessary step seems to be `dnf module install cri-o:1.13`. It seems that `dnf module install cri-o:1.14` works too.

**Output of `crio --version`:**

```
crio version 1.13.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by giuseppe** [comment]
we need to fix the documentation.  On Fedora 30 you'll first need to choose the module, so you can pick the version you prefer

**Comment by adelton** [comment]
The https://github.com/cri-o/cri-o/pull/2714 does not seem to work on Fedora 30 -- please see https://github.com/cri-o/cri-o/pull/2714#issuecomment-520754211.

**Comment by haircommander** [comment]
shoot, I had already subscribed to a module so I didn't error out. Waiting on 1.15 to be added to fedora, then I'll update

**Comment by adelton** [comment]
> shoot, I had already subscribed to a module so I didn't error out.

:-D

**Comment by michaelgugino** [comment]
cri-o 1.14 broken on F30 modular: https://bugzilla.redhat.com/show_bug.cgi?id=1743017

**Comment by blaise-sumo** [comment]
If I wanted to have this package in fedora ARM64, would I need to build from source?

**Comment by adelton** [comment]
I see aarch64 rpms in Fedora's koji, for example https://koji.fedoraproject.org/koji/buildinfo?buildID=1382517.

**Comment by dichen16** [comment]
```
● crio.service - Open Container Initiative Daemon
   Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-11-15 14:59:05 CST; 29s ago
     Docs: https://github.com/cri-o/cri-o
  Process: 11922 ExecStart=/usr/bin/crio $CRIO_STORAGE_OPTIONS $CRIO_NETWORK_OPTIONS $CRIO_METRICS_OPTIONS (code=exited, status=1/FAILURE)
 Main PID: 11922 (code=exited, status=1/FAILURE)
      CPU: 143ms

Nov 15 14:59:05 dilaptop systemd[1]: Starting Open Container Initiative Daemon...
Nov 15 14:59:05 dilaptop crio[11922]: time="2019-11-15 14:59:05.234129706+08:00" level=fatal msg="Invalid character(s) found in prerelease "module_f31""
Nov 15 14:59:05 dilaptop systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 14:59:05 dilaptop systemd[1]: crio.service: Failed with result 'exit-code'.
Nov 15 14:59:05 dilaptop systemd[1]: Failed to start Open Container Initiative Daemon.

```
Hi, @adelton 
the fc31 and fc30 both have this issue when using `dnf mudule` to install cri-o.

**Comment by adelton** [comment]
It's been brought to CRI-O Fedora maintainers as https://bugzilla.redhat.com/show_bug.cgi?id=1740730, https://bugzilla.redhat.com/show_bug.cgi?id=1743017, and https://bugzilla.redhat.com/show_bug.cgi?id=1754170.

**Comment by dougsland** [comment]
The Fedora documentation is fixed and all the listed bugs are closed as well. @adelton @haircommander @mrunalp @rhatdan please consider closing this one.

**Comment by adelton** [comment]
@dougsland, on Fedora 32, the steps from https://cri-o.io/ fail with
```
Error: Problems in request:
missing groups or modules: cri-o:1.14
```

**Comment by dougsland** [comment]
> @dougsland, on Fedora 32, the steps from https://cri-o.io/ fail with
> 
> ```
> Error: Problems in request:
> missing groups or modules: cri-o:1.14
> ```

Hi @adelton,

That's because 1.14 is not available for install, try a recent version as showed below.

# sudo dnf module list cri-o
Last metadata expiration check: 0:03:09 ago on Wed Apr 22 11:25:31 2020.
Fedora Modular 32 - x86_64
Name                                         Stream                                        Profiles                                       Summary                                                                                              
cri-o                                        1.11                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.13                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.15                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.16                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.17                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      

Fedora Modular 32 - x86_64 - Test Updates
Name                                         Stream                                        Profiles                                       Summary                                                                                              
cri-o                                        1.11                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.13                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.15                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.16                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.17                                          default                                        Kubernetes Container Runtime Interface for OCI-based containers                                      
cri-o                                        1.18                                          default                                        Kubernetes Container Runtime Interface for OCI-based container


Using recent version should work out of the box:

# cat /etc/os-release 
NAME=Fedora
VERSION="32 (Container Image)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Container Image)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container



# sudo dnf module list cri-o
Last metadata expiration check: 0:02:53 ago on Wed Apr 22 11:25:31 2020.
Fedora Modular 32 - x86_64
Name   Stream Profiles Summary                                                        
cri-o  1.11   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.13   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.15   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.16   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.17   default  Kubernetes Container Runtime Interface for OCI-based containers

Fedora Modular 32 - x86_64 - Test Updates
Name   Stream Profiles Summary                                                        
cri-o  1.11   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.13   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.15   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.16   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.17   default  Kubernetes Container Runtime Interface for OCI-based containers
cri-o  1.18   default  Kubernetes Container Runtime Interface for OCI-based containers

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled

# sudo dnf module enable cri-o:1.18
Last metadata expiration check: 0:04:09 ago on Wed Apr 22 11:25:31 2020.
Dependencies resolved.
===============================================================================================================================================================================================================================================
 Package                                                   Architecture                                             Version                                                    Repository                                                 Size
===============================================================================================================================================================================================================================================
Enabling module streams:
 cri-o                                                                                                              1.18                                                                                                                      

Transaction Summary
===============================================================================================================================================================================================================================================

Is this ok [y/N]: y
Complete!


# sudo dnf install cri-o
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
Last metadata expiration check: 0:04:33 ago on Wed Apr 22 11:25:31 2020.
Dependencies resolved.
===============================================================================================================================================================================================================================================
 Package                                                     Architecture                           Version                                                                      Repository                                               Size
===============================================================================================================================================================================================================================================
Installing:
 cri-o                                                       x86_64                                 2:1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b                                    updates-testing-modular                                  26 M
Installing dependencies:
 conmon                                                      x86_64                                 2:2.0.15-1.fc32                                                              updates-testing                                          42 k
 containernetworking-plugins                                 x86_64                                 0.8.5-1.1.gitf5c3d1b.fc32                                                    fedora                                                   11 M
 containers-common                                           x86_64                                 1:0.2.0-1.fc32                                                               updates-testing                                          65 k
 diffutils                                                   x86_64                                 3.7-4.fc32                                                                   fedora                                                  397 k
 libbsd                                                      x86_64                                 0.10.0-2.fc32                                                                fedora                                                  106 k
 libnet                                                      x86_64                                 1.1.6-19.fc32                                                                fedora                                                   64 k
 libnl3                                                      x86_64                                 3.5.0-2.fc32                                                                 fedora                                                  330 k
 libselinux-utils                                            x86_64                                 3.0-3.fc32                                                                   fedora                                                  160 k
 policycoreutils                                             x86_64                                 3.0-2.fc32                                                                   fedora                                                  210 k
 protobuf-c                                                  x86_64                                 1.3.2-2.fc32                                                                 fedora                                                   35 k
 rpm-plugin-selinux                                          x86_64                                 4.15.1-2.fc32.1                                                              fedora                                                   21 k
 runc                                                        x86_64                                 2:1.0.0-144.dev.gite6555cc.fc32                                              fedora                                                  2.7 M
 selinux-policy                                              noarch                                 3.14.5-32.fc32                                                               updates-testing                                         113 k
 selinux-policy-targeted                                     noarch                                 3.14.5-32.fc32                                                               updates-testing                                         8.1 M
 socat                                                       x86_64                                 1.7.3.4-2.fc32                                                               fedora                                                  304 k
Installing weak dependencies:
 container-selinux                                           noarch                                 2:2.132.0-1.fc32                                                             updates-testing                                          48 k
 criu                                                        x86_64                                 3.13-5.fc32                                                                  fedora                                                  492 k

Transaction Summary
===============================================================================================================================================================================================================================================
Install  18 Packages

Total download size: 50 M
Installed size: 226 M
Is this ok [y/N]: y   
Downloading Packages:
(1/18): conmon-2.0.15-1.fc32.x86_64.rpm                                                                                                                                                                        5.2 kB/s |  42 kB     00:08    
(2/18): container-selinux-2.132.0-1.fc32.noarch.rpm                                                                                                                                                            5.9 kB/s |  48 kB     00:08    
(3/18): containers-common-0.2.0-1.fc32.x86_64.rpm                                                                                                                                                              1.0 MB/s |  65 kB     00:00    
(4/18): selinux-policy-3.14.5-32.fc32.noarch.rpm                                                                                                                                                               1.6 MB/s | 113 kB     00:00    
(5/18): selinux-policy-targeted-3.14.5-32.fc32.noarch.rpm                                                                                                                                                       16 MB/s | 8.1 MB     00:00    
(6/18): cri-o-1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.x86_64.rpm                                                                                                                                               2.6 MB/s |  26 MB     00:10    
(7/18): diffutils-3.7-4.fc32.x86_64.rpm                                                                                                                                                                         49 kB/s | 397 kB     00:08    
(8/18): criu-3.13-5.fc32.x86_64.rpm                                                                                                                                                                             53 kB/s | 492 kB     00:09    
(9/18): libbsd-0.10.0-2.fc32.x86_64.rpm                                                                                                                                                                        625 kB/s | 106 kB     00:00    
(10/18): libnet-1.1.6-19.fc32.x86_64.rpm                                                                                                                                                                       371 kB/s |  64 kB     00:00    
(11/18): libnl3-3.5.0-2.fc32.x86_64.rpm                                                                                                                                                                        2.9 MB/s | 330 kB     00:00    
(12/18): libselinux-utils-3.0-3.fc32.x86_64.rpm                                                                                                                                                                1.4 MB/s | 160 kB     00:00    
(13/18): policycoreutils-3.0-2.fc32.x86_64.rpm                                                                                                                                                                 4.0 MB/s | 210 kB     00:00    
(14/18): protobuf-c-1.3.2-2.fc32.x86_64.rpm                                                                                                                                                                    419 kB/s |  35 kB     00:00    
(15/18): rpm-plugin-selinux-4.15.1-2.fc32.1.x86_64.rpm                                                                                                                                                         331 kB/s |  21 kB     00:00    
(16/18): socat-1.7.3.4-2.fc32.x86_64.rpm                                                                                                                                                                       2.8 MB/s | 304 kB     00:00    
(17/18): runc-1.0.0-144.dev.gite6555cc.fc32.x86_64.rpm                                                                                                                                                          12 MB/s | 2.7 MB     00:00    
(18/18): containernetworking-plugins-0.8.5-1.1.gitf5c3d1b.fc32.x86_64.rpm                                                                                                                                      1.0 MB/s |  11 MB     00:10    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                          1.1 MB/s |  50 MB     00:43     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Running scriptlet: selinux-policy-targeted-3.14.5-32.fc32.noarch                                                                                                                                                                         1/1 
  Preparing        :                                                                                                                                                                                                                       1/1 
  Installing       : libselinux-utils-3.0-3.fc32.x86_64                                                                                                                                                                                   1/18 
  Installing       : socat-1.7.3.4-2.fc32.x86_64                                                                                                                                                                                          2/18 
  Installing       : protobuf-c-1.3.2-2.fc32.x86_64                                                                                                                                                                                       3/18 
  Installing       : libnl3-3.5.0-2.fc32.x86_64                                                                                                                                                                                           4/18 
  Installing       : libnet-1.1.6-19.fc32.x86_64                                                                                                                                                                                          5/18 
  Installing       : libbsd-0.10.0-2.fc32.x86_64                                                                                                                                                                                          6/18 
  Installing       : criu-3.13-5.fc32.x86_64                                                                                                                                                                                              7/18 
  Installing       : diffutils-3.7-4.fc32.x86_64                                                                                                                                                                                          8/18 
  Installing       : policycoreutils-3.0-2.fc32.x86_64                                                                                                                                                                                    9/18 
  Running scriptlet: policycoreutils-3.0-2.fc32.x86_64                                                                                                                                                                                    9/18 
Created symlink /etc/systemd/system/sysinit.target.wants/selinux-autorelabel-mark.service → /usr/lib/systemd/system/selinux-autorelabel-mark.service.

  Installing       : rpm-plugin-selinux-4.15.1-2.fc32.1.x86_64                                                                                                                                                                           10/18 
  Installing       : selinux-policy-3.14.5-32.fc32.noarch                                                                                                                                                                                11/18 
  Running scriptlet: selinux-policy-3.14.5-32.fc32.noarch                                                                                                                                                                                11/18 
  Running scriptlet: selinux-policy-targeted-3.14.5-32.fc32.noarch                                                                                                                                                                       12/18 
  Installing       : selinux-policy-targeted-3.14.5-32.fc32.noarch                                                                                                                                                                       12/18 
  Running scriptlet: selinux-policy-targeted-3.14.5-32.fc32.noarch                                                                                                                                                                       12/18 
  Running scriptlet: container-selinux-2:2.132.0-1.fc32.noarch                                                                                                                                                                           13/18 
  Installing       : container-selinux-2:2.132.0-1.fc32.noarch                                                                                                                                                                           13/18 
  Running scriptlet: container-selinux-2:2.132.0-1.fc32.noarch                                                                                                                                                                           13/18 
  Installing       : runc-2:1.0.0-144.dev.gite6555cc.fc32.x86_64                                                                                                                                                                         14/18 
  Installing       : containernetworking-plugins-0.8.5-1.1.gitf5c3d1b.fc32.x86_64                                                                                                                                                        15/18 
  Installing       : containers-common-1:0.2.0-1.fc32.x86_64                                                                                                                                                                             16/18 
  Installing       : conmon-2:2.0.15-1.fc32.x86_64                                                                                                                                                                                       17/18 
  Installing       : cri-o-2:1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.x86_64                                                                                                                                                              18/18 
  Running scriptlet: cri-o-2:1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.x86_64                                                                                                                                                              18/18 
  Running scriptlet: selinux-policy-targeted-3.14.5-32.fc32.noarch                                                                                                                                                                       18/18 
  Running scriptlet: container-selinux-2:2.132.0-1.fc32.noarch                                                                                                                                                                           18/18 
  Running scriptlet: cri-o-2:1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.x86_64                                                                                                                                                              18/18 
  Verifying        : cri-o-2:1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.x86_64                                                                                                                                                               1/18 
  Verifying        : conmon-2:2.0.15-1.fc32.x86_64                                                                                                                                                                                        2/18 
  Verifying        : container-selinux-2:2.132.0-1.fc32.noarch                                                                                                                                                                            3/18 
  Verifying        : containers-common-1:0.2.0-1.fc32.x86_64                                                                                                                                                                              4/18 
  Verifying        : selinux-policy-3.14.5-32.fc32.noarch                                                                                                                                                                                 5/18 
  Verifying        : selinux-policy-targeted-3.14.5-32.fc32.noarch                                                                                                                                                                        6/18 
  Verifying        : containernetworking-plugins-0.8.5-1.1.gitf5c3d1b.fc32.x86_64                                                                                                                                                         7/18 
  Verifying        : criu-3.13-5.fc32.x86_64                                                                                                                                                                                              8/18 
  Verifying        : diffutils-3.7-4.fc32.x86_64                                                                                                                                                                                          9/18 
  Verifying        : libbsd-0.10.0-2.fc32.x86_64                                                                                                                                                                                         10/18 
  Verifying        : libnet-1.1.6-19.fc32.x86_64                                                                                                                                                                                         11/18 
  Verifying        : libnl3-3.5.0-2.fc32.x86_64                                                                                                                                                                                          12/18 
  Verifying        : libselinux-utils-3.0-3.fc32.x86_64                                                                                                                                                                                  13/18 
  Verifying        : policycoreutils-3.0-2.fc32.x86_64                                                                                                                                                                                   14/18 
  Verifying        : protobuf-c-1.3.2-2.fc32.x86_64                                                                                                                                                                                      15/18 
  Verifying        : rpm-plugin-selinux-4.15.1-2.fc32.1.x86_64                                                                                                                                                                           16/18 
  Verifying        : runc-2:1.0.0-144.dev.gite6555cc.fc32.x86_64                                                                                                                                                                         17/18 
  Verifying        : socat-1.7.3.4-2.fc32.x86_64                                                                                                                                                                                         18/18 

Installed:
  conmon-2:2.0.15-1.fc32.x86_64                                    container-selinux-2:2.132.0-1.fc32.noarch           containernetworking-plugins-0.8.5-1.1.gitf5c3d1b.fc32.x86_64           containers-common-1:0.2.0-1.fc32.x86_64          
  cri-o-2:1.18.0-0.1.rc1.module_f32+8645+a8dc4c4b.x86_64           criu-3.13-5.fc32.x86_64                             diffutils-3.7-4.fc32.x86_64                                            libbsd-0.10.0-2.fc32.x86_64                      
  libnet-1.1.6-19.fc32.x86_64                                      libnl3-3.5.0-2.fc32.x86_64                          libselinux-utils-3.0-3.fc32.x86_64                                     policycoreutils-3.0-2.fc32.x86_64                
  protobuf-c-1.3.2-2.fc32.x86_64                                   rpm-plugin-selinux-4.15.1-2.fc32.1.x86_64           runc-2:1.0.0-144.dev.gite6555cc.fc32.x86_64                            selinux-policy-3.14.5-32.fc32.noarch             
  selinux-policy-targeted-3.14.5-32.fc32.noarch                    socat-1.7.3.4-2.fc32.x86_64                        

Complete!
[root@efd8da27d7e5 /]#

**Comment by adelton** [comment]
> That's because 1.14 is not available for install, try a recent version as showed below.

I understand that. And this issue is about the instructions on https://cri-o.io/ which lead users the path of attempting the installation of 1.14. If `cri-o` does not and will not define the default stream, the page likely should spell out that `dnf module list cri-o` command so that the user has a way of figuring out which versions are available on a particular Fedora release.

**Comment by dougsland** [comment]
> > That's because 1.14 is not available for install, try a recent version as showed below.
> 
> I understand that. And this issue is about the instructions on https://cri-o.io/ which lead users the
> path of attempting the installation of 1.14. If `cri-o` does not and will not define the default stream,
> the page likely should spell out that `dnf module list cri-o` command so that the user has a way of
> figuring out which versions are available on a particular Fedora release.

Thanks for the clarification! Sent PR.

**Comment by dougsland** [comment]
@adelton PR merged. Thanks for the suggestion. Please consider closing this report.

**Comment by adelton** [comment]
Thank you.

**Comment by mykaul** [comment]
I'm unsure if there has been a change, but this doesn't work (Fedora 35). Running 'dnf module list cri-o' returns 'Error: no matching Modules to list'

**Comment by spdfnet** [comment]
It seems to me that using Suse's Kubic repos has been the only way for a while, regardless of distro.
Though, I agree that documentation should be clear about this.

**Comment by mykaul** [comment]
> I'm unsure if there has been a change, but this doesn't work (Fedora 35). Running 'dnf module list cri-o' returns 'Error: no matching Modules to list'

Just to complete the picture - installing the relevant packages directly from Koji (I picked latest 1.22) worked:
```
 sudo dnf install https://kojipkgs.fedoraproject.org//packages/cri-o/1.22.2/1.module_f35+13898+371726a8/x86_64/cri-o-1.22.2-1.module_f35+13898+371726a8.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/cri-tools/1.22.0/3.module_f35+13898+371726a8/x86_64/cri-tools-1.22.0-3.module_f35+13898+371726a8.x86_64.rpm
```

**Comment by mykaul** [comment]
> > I'm unsure if there has been a change, but this doesn't work (Fedora 35). Running 'dnf module list cri-o' returns 'Error: no matching Modules to list'
> 
> Just to complete the picture - installing the relevant packages directly from Koji (I picked latest 1.22) worked:
> 
> ```
>  sudo dnf install https://kojipkgs.fedoraproject.org//packages/cri-o/1.22.2/1.module_f35+13898+371726a8/x86_64/cri-o-1.22.2-1.module_f35+13898+371726a8.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/cri-tools/1.22.0/3.module_f35+13898+371726a8/x86_64/cri-tools-1.22.0-3.module_f35+13898+371726a8.x86_64.rpm
> ```

And for future reference - the modular repos were NOT enabled. On I've enabled them, things worked well:
```
[ykaul@ykaul guess]$ sudo dnf module list |grep cri
cri-o              1.19             default [d]                       Kubernetes Container Runtime Interface for OCI-based containers    
nodejs             12               default, development, minimal     Javascript runtime                                                 
nodejs             14               default, development, minimal     Javascript runtime                                                 
nodejs             15               default, development, minimal     Javascript runtime                                                 
nodejs             16               default, development, minimal     Javascript runtime                                                 
ruby               2.7              default [d]                       An interpreter of object-oriented scripting language               
ruby               3.0              default [d]                       An interpreter of object-oriented scripting language               
cri-o              1.19             default [d]                       Kubernetes Container Runtime Interface for OCI-based containers    
cri-o              1.20             default [d]                       Kubernetes Container Runtime Interface for OCI-based containers    
cri-o              1.21             default [d]                       Kubernetes Container Runtime Interface for OCI-based containers    
cri-o              1.22             default [d]                       Kubernetes Container Runtime Interface for OCI-based containers    
nodejs             12               default, development, minimal     Javascript runtime                                                 
nodejs             14               common [d], development, minimal  Javascript runtime                                                 
nodejs             15               default, development, minimal     Javascript runtime                                                 
nodejs             16               common [d], development, minimal  Javascript runtime                                                 
ruby               2.7              default [d]                       An interpreter of object-oriented scripting language               
ruby               3.0              default [d]                       An interpreter of object-oriented scripting language               
[ykaul@ykaul guess]$ sudo dnf module enable cri-o:1.22
Last metadata expiration check: 0:00:37 ago on Mon 28 Feb 2022 11:23:10 IST.
Dependencies resolved.
==============================================================================================================================================================================================================================================================================================================================
 Package                                                                       Architecture                                                                 Version                                                                       Repository                                                                     Size
==============================================================================================================================================================================================================================================================================================================================
Enabling module streams:
 cri-o                                                                                                                                                      1.22                                                                                                                                                             

Transaction Summary
==============================================================================================================================================================================================================================================================================================================================

Is this ok [y/N]: y
Complete!
```

**Comment by haircommander** [comment]
I'm glad you've figured it out @mykaul do you think there should be a documentation update for folks who run into this in the future?
