### ISSUE TITLE
Image pull metrics

### ISSUE THREAD

**Issue by ykoer** [cri-o/cri-o#2757]
We would like to collect the image pull time metrics with Prometheus. But it looks like Cri-o does not have those. Or did I overlooked it?

**Comment by ykoer** [comment]
@saschagrunert yes we were suggesting prometheus metrics. The reason is, that we have sometimes terrible pull times from a quay registry running on AWS. It would be great to have the possibility to create alerts.

**Comment by saschagrunert** [comment]
@ykoer the only metric we currently support if the cumulative operations time via the `pull_image` metric. Does this fit your needs or would you need it on a per-image basis?

**Comment by ykoer** [comment]
Let me try it out. But could not find the metric in Prometheus. Do you know if it is collected by default?

**Comment by saschagrunert** [comment]
> Let me try it out. But could not find the metric in Prometheus. Do you know if it is collected by default?

Depending on the distribution and package I would assume that it disabled by default. To enable it, you would have to pass the `--enable-metrics` flag to CRI-O, where the port can be changed via `--metrics-port=...`

**Comment by saschagrunert** [comment]
Apart from improving the metrics, I would bring this feature directly into Kubernetes to have a uniform API for it.

Reference https://github.com/kubernetes/kubernetes/issues/19077

**Comment by smarterclayton** [comment]
After spending a fair amount of time talking about this over the years I think this belongs in each container runtime.  CRI is too coarse to carry this metric and the implementation of each CRI will likely differ.  Also, the best metrics for this are going to be pretty deep in the stack (i.e. inside containers/storage) and likely be somewhat tied to the details of the storage layer.

I was going to bring this up with @mrunalp anyway (we've talked about it on and off for years now), but I think we should add the following metrics inside cri-o and assess their value, then make a general recommendation to other CRIs:

* bytes transferred during pull as a metric (actual bytes read for layers + manifests)
  * we can use this to derive instantaneous pull rate for a given node
  * enough cardinality (by registry?) to detect which registries are slow, without blowing up the cluster
* bytes not pulled for a given image, recorded at the time of pull (i.e. bytes not pulled to layering, or due to already being in the cache, likely as two separate labels)
* number of independent layer / blob reads at any given time (so we can detect when we are insufficiently or highly parallel)

The runtime operations metrics today in both crio and Kubelet can give you an idea, but not enough to answer the questions

a) is the amount of data pulled the problem, or the rate of pull from a registry
b) how efficient are my images on a node (how much overlap / sharing) such that someone could improve pull times just by reusing more common layers

This is part of a larger effort I'm trying to organize around reducing pod start times in general - pulls aren't the only component, but they are the most highly variable component.

**Comment by saschagrunert** [comment]
Thanks for the nice wrap-up @smarterclayton. I think we need the data in any case, independently if it gets exposed via the CRI or not. :+1:

**Comment by saschagrunert** [comment]
@smarterclayton @ykoer may I ask you to give #2912 a first look? It should address most of the needs, right?

>     * bytes not pulled for a given image, recorded at the time of pull (i.e. bytes not pulled to layering, or due to already being in the cache, likely as two separate labels)

This is currently not possible. We would need to enhance the progress reader even further to provide more detailed information.

**Comment by ykoer** [comment]
@saschagrunert sorry for the delayed answer. I was on on leave for a while. PR 2912 looks great. That is exactly what we need. I guess the extended image pull metrics will be available in a future OCP 4.2.x release, correct?

**Comment by saschagrunert** [comment]
> I guess the extended image pull metrics will be available in a future OCP 4.2.x release, correct?

No worries. :) I think it will be available on CRI-O 1.17 at the end of the year with Kubernetes 1.17. I'm not sure how OCP sticks to CRI-O/Kubernetes releases but I think the Red Hat maintainers can answer this question.

**Comment by paterczm** [comment]
Are there plans to include similar metric for image pushes?

**Comment by saschagrunert** [comment]
> Are there plans to include similar metric for image pushes?

We have no way to push images via the container runtime interface right now. Do you see a certain use case for such metrics?

**Comment by haircommander** [comment]
> @saschagrunert sorry for the delayed answer. I was on on leave for a while. PR 2912 looks great. That is exactly what we need. I guess the extended image pull metrics will be available in a future OCP 4.2.x release, correct?

This feature will not reach Openshift until 4.4

**Comment by paterczm** [comment]
> We have no way to push images via the container runtime interface right now. Do you see a certain use case for such metrics?

I forgot cri-o is just a runtime, I guess my question didn't make much sense. OpenShift provides build capabilities, so it does push images. OpenShift 3.x uses Docker for that, 4.x is using Buildah. The image uploads can be slow in our environments, looking for a way to track those.

**Comment by chinmaykhare** [comment]
I tested this in OCP 4.7 environment, but in prometheus was not able to find any **image pull time** metrics.

I wanted to have info on the time required to download an image. I'm i missing to interpret the output correctly?

Eg - `container_runtime_crio_image_pulls_by_name` is not showing the pull time

**Comment by saschagrunert** [comment]
@chinmaykhare those metrics are disabled in OpenShift right now:
https://github.com/openshift/cluster-monitoring-operator/blob/9f2908d296862befdc0f84e800ab0546e6feb12d/assets/control-plane/service-monitor-kubelet.yaml#L97-L98

More details about the reasoning can be found in https://github.com/cri-o/cri-o/issues/4982#issue-915165129
