### ISSUE TITLE
Why CRI-O require CRI-O wipe service?

### ISSUE THREAD

**Issue by Nefelim4ag** [cri-o/cri-o#3544]
I understood that `crio wipe` is similar to `docker system prune -af --volumes`

But i can't understand why CRI-O need that service on every machine restart and why CRI-O can't run without it (i'm talk about require= section in service)

Can someone explain please?

Thanks!

**Comment by haircommander** [comment]
it's not really necessary. Honestly, I've been meaning to drop the requires in this version. Sorry about that.

we use crio wipe in openshift to clear out nodes, because of how we upgrade between minor versions of kubernetes. If we didn't use crio wipe, containers and images would persist between versions and clog up nodes.

Though, for more crio installations, it's really not necessary and also is a source of headaches. I will put together a PR to drop the requirement.

Thanks for the question and issue

**Comment by saschagrunert** [comment]
I think if we create some upgrade path tests (however they may look like) then we would be able to drop the wiping completely. It’s not only about updating workloads, it’s also about which workloads to update and in which order. For example the API server should be the first one, right? 🙂
