### ISSUE TITLE
runtime validation: \"runc\" not found in $PATH: exec: \"runc\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by AkihiroSuda** [cri-o/cri-o#4069]
**Description**

CRI-O fails when `runc` binary is not present in `$PATH`, even when `[crio.runtime.runtimes]` doesn't contain `runc`

**Steps to reproduce the issue:**
1. Trigger Usernetes CI with CRIO_COMMIT= 267aa23eb538c3292ac4d254b8fb1b0ff6209697  (2020-08-11): https://github.com/rootless-containers/usernetes/pull/183

**Describe the results you received:**

```
...
Aug 12 07:31:41 a9fab463e670 crio.sh[449]: time="2020-08-12 07:31:41.219385057Z" level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
Aug 12 07:31:41 a9fab463e670 crio.sh[449]: time="2020-08-12 07:31:41.219476364Z" level=fatal msg="Validating runtime config: runtime validation: \"runc\" not found in $PATH: exec: \"runc\": executable file not found in $PATH"
Aug 12 07:31:41 a9fab463e670 systemd[50]: u7s-crio.service: Main process exited, code=exited, status=1/FAILURE
```

**Describe the results you expected:**

Should work

**Additional information you deem important (e.g. issue happens only occasionally):**

It had been working with c1d5921e48281d089eecc19ccddf1c72bb2f54b3 (2020-07-28).

Seems a regression in c1d5921e48281d089eecc19ccddf1c72bb2f54b3...267aa23eb538c3292ac4d254b8fb1b0ff6209697

**Comment by AkihiroSuda** [comment]
Regression in 91d3d2791 (https://github.com/cri-o/cri-o/pull/3772)

**Comment by haircommander** [comment]
you need to also set
```
[crio.runtime]
default_runtime = "crun"
```

**Comment by AkihiroSuda** [comment]
Yes, set, but still requires runc
https://github.com/rootless-containers/usernetes/blob/6b7c064bf5ef4161cef3453bb858b7d6e05d9628/boot/crio.sh#L42

**Comment by haircommander** [comment]
@harche PTAL

**Comment by saschagrunert** [comment]
Xref for the discussion: https://github.com/cri-o/cri-o/pull/3772#discussion_r431620595

**Comment by harche** [comment]
```diff
diff --git a/pkg/config/config.go b/pkg/config/config.go
index 446fff5ba..5936df00a 100644
--- a/pkg/config/config.go
+++ b/pkg/config/config.go
@@ -452,11 +452,18 @@ func (c *Config) UpdateFromFile(path string) error {
        t := new(tomlConfig)
        t.fromConfig(c)
 
-       _, err = toml.Decode(string(data), t)
+       metadata, err := toml.Decode(string(data), t)
        if err != nil {
                return fmt.Errorf("unable to decode configuration %v: %v", path, err)
        }
 
+       runtimesKey := []string{"crio", "runtime", "default_runtime"}
+       if metadata.IsDefined(runtimesKey...) {
+               if t.Crio.Runtime.RuntimeConfig.DefaultRuntime != defaultRuntime {
+                       delete(c.Runtimes, defaultRuntime)
+               }
+       }
+
```

I did following tests with this change,

1. Start CRIO by configuring `crun` as the `default_runtime` (with and without having `runc` on the host)
```bash
$ cat /tmp/10-crun.conf 
[crio.runtime]
  default_runtime = "crun"
  [crio.runtime.runtimes]
    [crio.runtime.runtimes.crun]
      runtime_path="/usr/bin/crun"
```
**Result** -  CRIO starts fine. But it will remove the default runtime entry `runc` that came from [here](https://github.com/cri-o/cri-o/blob/master/pkg/config/config.go#L37). If we decide to go with the above change, then we can explicitly document that if the `default_runtime` is changed, then `runc` will be removed (which came by default) and if they wish to use `runc` as a non-default runtime they should add a drop in config just like any other runtime would have to.


2. Start CRIO by adding `crun` but NOT setting it as `default_runtime` (`runc` is present on the host)
```bash
$ cat /tmp/10-crun.conf 
[crio.runtime]
  [crio.runtime.runtimes]
    [crio.runtime.runtimes.crun]
      runtime_path="/usr/bin/crun"
``` 
**Result** - CRIO starts fine in this case too, but it will retain the old `runc` entry since `default_runtime` was not modified. 

This way we can retain the changes from https://github.com/cri-o/cri-o/commit/91d3d2791ce348098ba0a6a731f5809a060a1a67 that simplify adding the additional runtime to crio as well as address the issue reported by @AkihiroSuda 

@saschagrunert @mrunalp @haircommander Let me know what do you think.

**Comment by saschagrunert** [comment]
> @saschagrunert @mrunalp @haircommander Let me know what do you think.
Sounds like a feasible solution to me, if @AkihiroSuda is also fine with it. :+1:

**Comment by AkihiroSuda** [comment]
SGTM
