### ISSUE TITLE
Image manifests are requested twice

### ISSUE THREAD

**Issue by fabioluz** [cri-o/cri-o#5039]
**Description**

Image manifests are being requested twice.

**Steps to reproduce the issue:**
1. Start `crio`
2. Configure a way to inspect all HTTP requests. e.g. ngrok
3. Use `crictl` to pull an image

**Describe the results you received:**

Image `manifests/tag` and `manifests/sha` are being requested twice. Anybody using CRI-O will be rate-limited twice as fast on DockerHub.

See in the image below
![image](https://user-images.githubusercontent.com/5049361/123642548-ca8d0480-d7f9-11eb-8099-526646dc9aec.png)

**Describe the results you expected:**

The `manifests/tag` and `manifests/sha` should be requested only once per pull.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.21.1
Version:       1.21.1
GitCommit:     f6353417d762bb388d529d054414ad75cc3fff0f
GitTreeState:  clean
BuildDate:     2021-06-24T17:04:46Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by haircommander** [comment]
interesting, thanks for doing this investigation!

@vrothberg @saschagrunert @umohnani8 do y'all think this should be moved to c/image for further investigation?

**Comment by vrothberg** [comment]
Yes, moving over to c/image.

**Comment by vrothberg** [comment]
I don't seem to be able to move it.  Not sure if it's a glitch in the GitHub UI or if I am lacking permissions.

**Comment by haircommander** [comment]
I don't think it's movable because this is in a different repo actually. @fabioluz could you open an issue in github.com/containers/image please

**Comment by fabioluz** [comment]
I would be happy in doing it @haircommander but is it really case here? Skopeo also uses `containers/image` internally and it does not request the manifests twice.

**Comment by wgahnagl** [comment]
I'll take a look at this!

**Comment by mtrmac** [comment]
This is fairly likely to be https://github.com/cri-o/cri-o/blob/effa584c039d3ee519afb08fcad9f449d52a13a6/server/image_pull.go#L129-L158 .

**Comment by wgahnagl** [comment]
> This is fairly likely to be
> 
> https://github.com/cri-o/cri-o/blob/effa584c039d3ee519afb08fcad9f449d52a13a6/server/image_pull.go#L129-L158
> .

:thinking: this is weird, because I went back in the git history to right before this change and reverted it, but the logs show that the manifest is still getting requested twice.
It seems to be an isssue going back even further than even 2018 

Any ideas for where I should look next? 
```73.218.26.115 - - [10/Sep/2021:15:51:02 +0000] "GET /v2/ HTTP/1.1" 401 4 "cri-o/1.10.0-dev go/go1.11.1 os/linux arch/amd64" (Upstream: 401 from nginx/1.12.1)
73.218.26.115 - - [10/Sep/2021:15:51:03 +0000] "GET /v2/aptible/busybox/manifests/latest HTTP/1.1" 200 31496 "cri-o/1.10.0-dev go/go1.11.1 os/linux arch/amd64" (Upstream: 200 from nginx/1.12.1)
73.218.26.115 - - [10/Sep/2021:15:51:04 +0000] "GET /v2/ HTTP/1.1" 401 4 "Go-http-client/1.1" (Upstream: 401 from nginx/1.12.1)
73.218.26.115 - - [10/Sep/2021:15:51:06 +0000] "GET /v2/aptible/busybox/manifests/latest HTTP/1.1" 200 31496 "Go-http-client/1.1" (Upstream: 200 from nginx/1.12.1)
73.218.26.115 - - [10/Sep/2021:15:51:06 +0000] "GET /v2/ HTTP/1.1" 401 4 "cri-o/1.10.0-dev go/go1.11.1 os/linux arch/amd64" (Upstream: 401 from nginx/1.12.1)
73.218.26.115 - - [10/Sep/2021:15:51:08 +0000] "GET /v2/aptible/busybox/manifests/latest HTTP/1.1" 200 31496 "cri-o/1.10.0-dev go/go1.11.1 os/linux arch/amd64" (Upstream: 200 from nginx/1.12.1)
```

**Comment by mtrmac** [comment]
That was just intended to point at the code _location_, not at the commit that introduced it. The concept of checking for presence before pulling has existed in CRI-O certainly for > 2 years.

The point about different user agents surprises me a bit, though. Either way, ultimately one way to tell for sure would be to hook the HTTP client implementation in the standard library or something like that and just capture URLs+backtraces in there.

**Comment by wgahnagl** [comment]
while trying to find where the request is getting called, I found this in the image/copy dependency 
https://github.com/cri-o/cri-o/blob/8e3cdc940aec6ad68cb2c123ab16e3bcb462286d/vendor/github.com/containers/image/v5/copy/copy.go#L722 
it looks to me like the manifest is getting requested twice here, because it's unable to determine if the registry accepts schema 1 or 2, and needs to make two requests to determine which one it needs.

**Comment by mtrmac** [comment]
That’s completely unrelated:
- It talks about capabilities of the _copy destination_, if it is a registry; in the pull path discussed here, the registry is a source, not a destination. The c/storage destination, implemented in the same project as c/image/storage, can accept all supported image formats without conversion, so that loop will always succeed on a first try.
- The manifest access of the source image is mediated via `c/image/image.UnparsedInstance`, which ensures the manifest is only fetched once (this is a critical property for signature validation, and if that doesn’t work). So the number of iterations of that loop does not matter anyway.

---

Above, I have pointed at `StorageImageServer().PrepareImage`→`NewImage`→…`unparsed.Manifest`→`dockerImageSource.GetManifest`, and `StorageImageServer().PullImage`→`copy.Image`, each independently reading the image manifest. Why is this not the cause of reading the manifest twice, or not relevant to this issue?

---

> Either way, ultimately one way to tell for sure would be to hook the HTTP client implementation in the standard library or something like that and just capture URLs+backtraces in there.

Or start with hooking `c/image/docker/dockerImageSource.fetchManifest`, and log the full request context and backtrace to a file, or something like that. Does _that_ show the duplicate accesses? If it does, what are the two code paths? (If not, reading any code in c/image is unlikely to explain the duplicate accesses.)

I mean, reading the code to understand how this all fits together is certainly useful, but it seems to me that there are fairly direct ways to let the computer collect pointers at the relevant code paths, easier than fully understanding the ~10k lines of code involved in the CRI-O + c/image copy implementation.

**Comment by vrothberg** [comment]
> Above, I have pointed at StorageImageServer().PrepareImage→NewImage→…unparsed.Manifest→dockerImageSource.GetManifest, and StorageImageServer().PullImage→copy.Image, each independently reading the image manifest. Why is this not the cause of reading the manifest twice, or not relevant to this issue?

I concur with @mtrmac.

The crux of the matter is the `PrepareImage` check _before_ copying the image.  That makes 1 request if the image is already present in the local storage and 2 requests if the image must be pulled.

Podman (or libimage) performs logically the same checks BUT it requests the manifest exactly once (or not at all depending on the pull policy).  CRI-O deals with images as strings but it should really be passing around a `c/image/v5/types.ImageReference` such that we can make use of caching.  While I would love to have CRI-O using libimage, I think it would be cheaper to pass around references instead of strings which may require changing some of CRI-O's (internal) APIs.

**Comment by mtrmac** [comment]
> CRI-O deals with images as strings but it should really be passing around a `c/image/v5/types.ImageReference` such that we can make use of caching.

While I always prefer using `ImageReference` over strings, it’s not clear to me how that would prevent the double manifest access in this case. The two accesses happen because the check for an image that is present and the same involve a `ref.NewImage`, and `copy.Image` internally does a `ref.NewImageSource` etc — and caching of the manifest (an implementation detail! not contractual! not even expected to be done by a transport!) happens in a `dockerImageSource`, not  in `dockerImageReference`. So it’s, AFAIK, not possible to do a check of image existence before `copy.Image` in a way that only fetches the manifest once. Am I missing something?

---

(That said, I’m also not sure if the existence pre-check actually makes a performance difference. I’m not sure if it has ever been measured. Maybe we can just get away with `copy.Image` doing the layer existence checks as usual, or maybe with `copy.Options.OptimizeDestinationImageAlreadyExists`. But that’s two or three steps ahead of the established set of facts.)

**Comment by vrothberg** [comment]
@mtrmac, I may need to look deeper.  I checked with Podman `podman create --pull newer $IMAGE` and the manifest is fetched exactly once AFAICS.

**Comment by mtrmac** [comment]
AFAICS https://github.com/containers/common/blob/161e078e4c7f4839038ddf339bb28611a4e018dc/libimage/image.go#L773-L778 can also make a remote request. (But it’s cheaper in that it compares manifest digests, not config digests — at the cost of possibly pulling in more cases.)

**Comment by vrothberg** [comment]
> AFAICS https://github.com/containers/common/blob/161e078e4c7f4839038ddf339bb28611a4e018dc/libimage/image.go#L773-L778 can also make a remote request. (But it’s cheaper in that it compares manifest digests, not config digests — at the cost of possibly pulling in more cases.)

Yes but it only fetches the manifest once but I am not yet entirely sure why.  I saw some caching in the docker source which is why I thought that's the reason

**Comment by vrothberg** [comment]
Yes, indeed the manifest blob is cached.

github.com/containers/image/v5/docker.dockerReference.NewImageSource -> github.com/containers/image/v5/docker.newImageSource -> github.com/containers/image/v5/docker.newImageSourceAttempt -> github.com/containers/image/v5/docker.(*dockerImageSource).ensureManifestIsLoaded -> github.com/containers/image/v5/docker.(*dockerImageSource).fetchManifest

Any future calls on GetManifest() return the cached blob.

> But it’s cheaper in that it compares manifest digests, not config digests — at the cost of possibly pulling in more cases.

I wonder why comparing config digests is considered safe.  A manifest could ship with annotations; aren't these ignored when only looking at config digests?

**Comment by mtrmac** [comment]
> [`NewImageSource` → … → `ensureManifestIsLoaded`
>
> Any future calls on GetManifest() return the cached blob.

Yes, but that’s within a _single_ `dockerImageSource` (via `dockerImageReference.NewImage{,Source}`). `hasDifferentDigestWithSystemContext` creates one `dockerImageSource`, and `copy.Image` creates an independent one.

The CRI-O situation is structurally similar: Two `dockerImageSource` objects.

---

> I wonder why comparing config digests is considered safe. A manifest could ship with annotations; aren't these ignored when only looking at config digests?

The formats that do have a separate config also carry RootFS.DiffID values (uncompressed layer digests) in the config, so the same config digest means both the same image config and same image layers.

There could be different manifests that point to the same config+layers (with different manifest formatting, different manifest annotations, differently-compressed layers), but I don’t think that makes a semantic difference right now; in particular we don’t use the manifest annotations for anything, to my knowledge. I.e. it would not be truly safe for `skopeo copy`, but it is safe for pulls.

Ultimately c/storage defines image ID = config digest if it exists, so a pull always deduplicates by config digest, and doing it in CRI-O is not grossly incorrect for this reason already (but it _could_ result in not recording a specific manifest, or a manifest digest, or maybe a set of signatures??, in the local c/storage metadata store).

**Comment by vrothberg** [comment]
> Yes, but that’s within a single dockerImageSource (via dockerImageReference.NewImage{,Source}). hasDifferentDigestWithSystemContext creates one dockerImageSource, and copy.Image creates an independent one.

That's not what I see in my logs.  I patched `fetchManifest` and see it executed exactly once in Podman.  Could you double check to make sure I am not doing something silly?

**Comment by wgahnagl** [comment]
hey, any updates on this?
@vrothberg @mtrmac

**Comment by vrothberg** [comment]
I still think that using `c/image/v5/types.ImageReference` instead of strings will resolve the issue.  The manifest is cached, so it will be fetched once.

**Comment by mtrmac** [comment]
> I still think that using `c/image/v5/types.ImageReference` instead of strings will resolve the issue.

The `c/image/docker` implementation of `ImageReference` is clearly stateless, and there is no cross-`ImageSource` manifest cache. I don’t see how that could make a difference.

**Comment by mtrmac** [comment]
> hey, any updates on this?

“Updates” of what kind?

We have pointed at the CRI-O code that probably causes this. Have you verified this, and/or proven that to be inaccurate?

If it is accurate, it’s up to CRI-O to decide whether it wants this heuristic or not. (The history of that heuristic can probably be found through Git history + GitHub discussions.)

What work have you done on either, and what questions are unresolved?

**Comment by vrothberg** [comment]
> > I still think that using `c/image/v5/types.ImageReference` instead of strings will resolve the issue.
> 
> The `c/image/docker` implementation of `ImageReference` is clearly stateless, and there is no cross-`ImageSource` manifest cache. I don’t see how that could make a difference.

See comment https://github.com/cri-o/cri-o/issues/5039#issuecomment-934432997.  I see it executed exactly once.

**Comment by mtrmac** [comment]
I completely believe you that that’s what you see. I can’t see how using `ImageReference` can be how that is caused.

**Comment by haircommander** [comment]
Independently of whether the issue is `ImageReference` or some other code block, all other container managers use libimage to do their image management. It's been in the backlog for a while to port CRI-O to it. To me, it makes sense to take this bug as a chance to unify the code and port CRI-O over to libimage, which (I can guess) could fix this bug, or at least reveal the source

**Comment by mtrmac** [comment]
AFAIK libimage does not do the same-config-digest optimization; so, yes, this would have to be “dealt with” during the port to libimage. At that time, by accident or design, the one porting the code could decide to drop that optimization; but if it we instead decided to continue to have this optimization, I currently can’t see how porting would change the (c/image-design-imposed) need to fetch the manifest twice.

(Or there’s something about the situation, or something clever libimage does, that I’m missing.)

**Comment by wgahnagl** [comment]
manifests being requested twice is intentional due to an optimization, and switching over to libimage doesn't appear to be able to resolve the issue either without getting rid of the optimization.
