### ISSUE TITLE
Apt upgrade results in "File has unexpected size"

### ISSUE THREAD

**Issue by chrisromano** [cri-o/cri-o#5470]
**Description**
Upgrading cri-o via apt on Ubuntu 20.04 fails. This appears to be nearly identical to the problem referenced in #5343 

**Steps to reproduce the issue:**
1. Installed Ubuntu 20.04 repositories according to cri-o documentation
2. Attempt to install or upgrade cri-o via apt

**Describe the results you received:**
```
Get:1 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04  cri-o 1.22.1~0 [20.1 MB]
Err:1 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04  cri-o 1.22.1~0
  File has unexpected size (20119660 != 20117328). Mirror sync in progress? [IP: 91.193.113.70 443]
  Hashes of expected file:
   - SHA256:0d05dddcc9b2fc9fb134ff528a1162e739a5e9f2a0b6c855d7b5f6293566dbd0
   - SHA1:32a569122deb55ab92140aee3bb03d23a1b86a58 [weak]
   - MD5Sum:6679f40b5397e034dccafa81c378b4b1 [weak]
   - Filesize:20117328 [weak]
E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/amd64/cri-o_1.22.1~0_amd64.deb  File has unexpected size (20119660 != 20117328). Mirror sync in progress? [IP: 91.193.113.70 443]
   Hashes of expected file:
    - SHA256:0d05dddcc9b2fc9fb134ff528a1162e739a5e9f2a0b6c855d7b5f6293566dbd0
    - SHA1:32a569122deb55ab92140aee3bb03d23a1b86a58 [weak]
    - MD5Sum:6679f40b5397e034dccafa81c378b4b1 [weak]
    - Filesize:20117328 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Output of `crio --version`:**
```
crio version 1.22.0
Version:          1.22.0
GitCommit:        6becad23eadd7dfdd25fd8df386bf3b706cf7758
GitTreeState:     clean
BuildDate:        2021-09-17T19:31:48Z
GoVersion:        go1.16.8
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

**Comment by haircommander** [comment]
yeah this problem pops up from time to time as the OBS mirrors get stale. I can double check the builds but I don't know if there's anything I can do from my side

**Comment by GusTheSadGeek** [comment]
I have been bitten by this too. Same mirror - provo-mirror.opensuse.org  - but xUbuntu_18.04 in my case.

**Comment by kon-s** [comment]
It looks like your releasing new versions of the package using the same version number as the old package released previously rather than incrementing the version?
using wget to download the package from 2 different systems (that seem to redirect to different mirrors) I see:
2021-12-03 13:40:54 (7.76 MB/s) - ‘cri-o_1.22.1~0_amd64.deb’ saved [20111360/20111360]]
ls -l cri-o_1.22.1~0_amd64.deb
-rw-rw-r-- 1 xxx xxx 20111360 Nov 17 02:44 cri-o_1.22.1~0_amd64.deb
And:
2021-12-03 13:41:37 (7.67 MB/s) - ‘cri-o_1.22.1~0_amd64.deb’ saved [20108032/20108032]
ls -l cri-o_1.22.1~0_amd64.deb 
-rw-rw-r-- 1 xxx xxx 20108032 Nov 30 01:09 cri-o_1.22.1~0_amd64.deb

**Comment by haircommander** [comment]
hm, I do admit I haven't bumped the value after the tilde in for deb based systems if I update the build after it was originally built. I am in the process of updating the latest branches of each release, which will hopefully trickle down to each of the mirrors and fix this problem.

**Comment by haircommander** [comment]
are folks still seeing this issue?

**Comment by kon-s** [comment]
I no longer see an issue since the latest release and I think as long as you continue to bump the version number whenever you release a new version of a package I think the same issue should not re-occur. Thanks.

**Comment by kon-s** [comment]
It would also be helpful if in future the older minor versions were left available too for a while at least so that people can continue to use and install those versions while they go through testing and change control processes of the latest version in development environments. ( I realise that was not a good idea on this occasion )

**Comment by haircommander** [comment]
what minor version are you looking for? We currently do save them, you can see the list [here](https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers:stable) and follow [the instructions for specific releases](https://github.com/cri-o/cri-o/blob/main/install.md#supported-versions)  to install :)

**Comment by kon-s** [comment]
We are again now seeing an update to the package but the same version number being used:
-rw-rw-r-- 1 xxx xxx 20106072 Dec  3 20:42 cri-o_1.22.1~1_amd64.deb
-rw-rw-r-- 1 xxx xxx 20114532 Dec  7 23:56 cri-o_1.22.1~1_amd64.deb
