### ISSUE TITLE
[RFE] Event API for container lifecycle events

### ISSUE THREAD

**Issue by thediveo** [cri-o/cri-o#5609]
The [CRI API](https://github.com/kubernetes/cri-api) today is (if I'm not mistaken) on purpose design from the perspective of the k8s kubelet that uses a polling model to supervise container runtimes.

In some use cases, such as OT (operation technology) workloads, it becomes necessary to deploy system (worker node and work load) diagnosis tools for Linux kernel-level resources (namespaces, processes, cgroups, ...), where these resources can be related to the user-space container elements. At the moment, these tools need to use the CRI API of cri-o and thus constantly poll for container information. This causes additional load on the hosts, potentially more load compared to a kublet where the latter might operate slower poll cycles, whereas diagnosis tools might need tighter polling loops.

Some container engines, namely dockerd and containerd offer event streaming APIs, including event filtering at the event source. This allows clients to require only low system resources when matching events get sent. One such example might be monitoring the container lifecycle only for the phases where container processes exist.

Could cri-o support its own event (streaming) API in addition to the CRI API, preferably including event filtering at the source?

**Comment by harche** [comment]
Thanks @TheDiveO for submitting this issue. Coincidentally, I have been experimenting with the idea of adding events stream from the runtime to the kubelet. Its still in it's early stage, envisioning how the CRI API should look like for supporting the such an event stream. 

- API method - https://github.com/harche/kubernetes/blob/event_pleg/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L36

- Method argument for filter events - https://github.com/harche/kubernetes/blob/event_pleg/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L134

- Method response (stream) - https://github.com/harche/kubernetes/blob/event_pleg/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L137


I would love to get your feedback on the above interface. We can use this issue to discuss this experimental work going forward. 

/cc @mrunalp @haircommander

**Comment by TheDiveO** [comment]
@harche thank you very much for this quick first response and offering to discuss it further, I highly appreciate this!

Not surprisingly, we probably come from different use cases (which is good), so I need to explain mine a little bit further. In my case, I'm not monitoring an individual container instance, but instead a specific set of `ContainerEventType`s. This includes containers being started and which I didn't knew beforehand. For illustration containerd's event API as used in my [whalewatcher github project](https://github.com/TheDiveO/whalewatcher/blob/99f7d7f4186c74a9f49567d5d029b135b026b808/engineclient/containerd/containerd.go#L243) might hopefully serve well (but not implying in any way that cri-o's should be the same):

```go
evs, errs := cw.client.EventService().Subscribe(ctx,
	// please note that strings need to be enclosed in quotes, otherwise
	// silent fail...
	`topic=="/tasks/start"`,
	`topic=="/tasks/exit"`,
	`topic=="/tasks/paused"`,
	`topic=="/tasks/resumed"`)
```

At the moment, `GetEventsFilter` could support my use case if it will accept an empty `id` field meaning "all containers". If possible, I would find it helpful not least to filter out events before needing to stream them to consumers of `GetEvents` if there could be a more general filter mechanism. As far as my limited understanding of `containerd`'s architecture goes, its `EventService` is a separate service, much like cri-o's `RuntimeService` and `ImageService`. While I personally don't have any use yet for events related to images, etc., I like this more general approach, including the hierarchical "topic" design. This allows for flexible use ... after reading the source code in order to find out their correct syntax :grin:

What do you think of such a more general topic-based approach as found in `containerd`?

Having labels reported as part of events would be a bonus to me, but I could also live without for the price of having to do a separate query on the selected lifecycle topics. The labels currently allow me to especially track composer-related container projects, but this doesn't look like a real use case for cri-o. However, there might be other uses, such as easily mapping container events to the aggregating pods and their namespaces.

**Comment by harche** [comment]
> What do you think of such a more general topic-based approach as found in containerd?

Containerd is composed of several independent `plugins` that need much more richer eventing mechanism. CRI has a sharp focus on being the interface between the kubelet and the runtime (like `cri-o` or `containerd`). So while designing the `events` interface for the CRI we need to keep that in mind.  

But everything is still it's early stage, and nothing is set on the stone yet (in fact far from it). So we would continuously make changes in iterations until we see something that does the job and fits well within the intended use of the CRI interface. 

Having said that, I am about to make some minor changes to the API. I will post it here for review once they are ready.

**Comment by TheDiveO** [comment]
_Revisiting the current draft, I notice that it currently can only report the demise of containers (https://github.com/harche/kubernetes/blob/d6cada8abc474551c461b3fc1fe41ac5356c522b/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L153), but not newly created or started containers.

In my use cases I need events for new containers, and in particular after the initial container process has been started, so its PID is known. Without this event, trying to track container workload would still require polling for new containers so that the event API wouldn't be of much use then.

**Comment by harche** [comment]
Thanks @TheDiveO, I have added `CREATED` and `STARTED` to the [ContainerEventType](https://github.com/harche/kubernetes/blob/event_pleg/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L151)

cc @haircommander

**Comment by harche** [comment]
Rough skeleton code - https://github.com/harche/cri-o/commit/0da45f74196ca9e2615a7d1146d930f986591c69

**Comment by haircommander** [comment]
I can't seem to figure it out based on the gRPC docs: if two clients request the events, is it up to the server to send each the set of new events each requested, or does gRPC somehow handle that? as in, if I have events ["create", "start"], and client A requests after "create", is it our job to only send client A "start", and client B ["create", "start"]

**Comment by TheDiveO** [comment]
my limited understanding is that gRPC provides the "streams" for th results, separately. So the server has open long-running responses and thus needs to handle filtering itself, according to each individual response (~session). I didn't notice anything in the gRPC layer.

If I'm not mistaken, https://github.com/containerd/containerd/blob/7078e50e2685556efd3f2dbd97b019e87452aeab/services/events/service.go#L92 is the server side implementation of containerd's Subscribe gRPC method. https://github.com/containerd/containerd/blob/release/1.6/events/exchange/exchange.go is what containerd call its internal "exchange" that looks to me like an event broker. Now, each individual Subscribe gRPC call Subscribe()s to this exchange and receives a channel for events, with the exchange doing the filtering. The Subscribe gRPC call then keeps on running as long as the event channel isn't closed and plumbs the events it receives from the exchange into the gRPC call's result stream.

**Comment by thediveo** [comment]
Is there a comparably simple way I could test drive your changes on a local development system, with a simple cri-o binary?

**Comment by harche** [comment]
> Is there a comparably simple way I could test drive your changes on a local development system, with a simple cri-o binary?

You will have to start the crio and then run local hack k8s cluster. e.g. https://github.com/cri-o/cri-o/tree/release-1.21#running-kubernetes-with-cri-o

**Comment by harche** [comment]
@thediveo BTW, there is another PRs where CRI related discussions are taking place - https://github.com/kubernetes/kubernetes/pull/110165

**Comment by thediveo** [comment]
thank you very much for the pointer!

**Comment by thediveo** [comment]
This has landed in the CRI v1 API and also in containerd. I'm now trying to use it. Thank you very much!

**Comment by lovishbatra10** [comment]
Hi @thediveo I noticed that the event streaming interface supported by CRI v1 API uses streams from containerd runtimes. Does cri-o runtime provide event streams as well which can be used by CRI API?

**Comment by thediveo** [comment]
@lovishbatra10 yes, it does. You'll need to enable them Evented PLEG API though, as otherwise you'll get back a stream and only "EOF" upon trying to read the next event.

```toml
# /etc/crio/crio.toml
	[crio.runtime]
	enable_pod_events=true
```

In case you want to see code, please have a look at the CRI engine adapter I wrote for tracking the container workload via the events; for starters, please see here: https://github.com/thediveo/whalewatcher/blob/master/engineclient/cri/cri.go

**Comment by AbetangJoseph** [comment]
Reading this was informative. @thediveo @harche 🙌🏽👏🏽
