### ISSUE TITLE
Checkpoint/Restore not working with cgroup v2 and Kubernetes

### ISSUE THREAD

**Issue by adrianreber** [cri-o/cri-o#6894]
### What happened?

This is mainly for tracking.

Although restoring a container in Kubernetes with cgroup v2 works the container will be immediately killed by Kubernetes as CRIU will restore the container in the old cgroup.

Outside of Kubernetes the behaviour cannot be seen as it seems only Kubernetes kills processes in unknown cgroups.

CRIU stores information about the cgroup during checkpointing and restores that information. I am not sure why this error cannot be seen with cgroup v1.

Fortunately runc has a fix for this problem in the merged PR https://github.com/opencontainers/runc/pull/3546.

Unfortunately this fix has not made its way into one of the existing runc releases, yet.

@kolyshkin any ideas when the `ignore` setting for cgroups will appear in a runc release?

**Comment by github-jyq** [comment]
Hi! Adrianreber! @adrianreber 
I meet the same problem just like MaxFuhrich @MaxFuhrich , the process that creates the problem is the same and I alse reference the blog The process that creates the problem is the same.
The difference is that I use centos7 and cgroupv1 .
![image](https://github.com/cri-o/cri-o/assets/81799971/495021c1-e663-4608-8482-75677a960bdc)

As a result , it doesn't seem to be problem of cgroupv1.
And I can restore a pod at one of my node but others not to restore with problem as follows just like MaxFuhrich:
![image](https://github.com/cri-o/cri-o/assets/81799971/9c57e6e9-384d-4069-b1bd-abb4801d2dfc)
And I create a issue https://github.com/cri-o/cri-o/issues/7349 to describe my problem before see this one.
