### ISSUE TITLE
Error on restoring customized mysql application via Kubernetes C/R

### ISSUE THREAD

**Issue by varungup90** [cri-o/cri-o#6972]
### What happened?

We run a customized mysql application internally. Checkpoint and Restore works for open-source mysql. For our internal application, I ran into the issue for FD limit when doing checkpoint, but that issue is fixed following https://github.com/cri-o/cri-o/issues/6936#issuecomment-1553533775 recommendation. After checkpoint, I created an image using buildah (following this [tutorial](https://martinheinz.dev/blog/85)). Now I am trying to restore and getting an error but error message is not descriptive enough. Attached the log file for CRIU.

### What did you expect to happen?

I expect the checkpoint and restore to work. It works with open-source mysql application but is having issue with internal customized mysql.

### How can we reproduce it (as minimally and precisely as possible)?

I am following this [tutorial](https://martinheinz.dev/blog/85) for C/R using K8s. 

### Anything else we need to know?

Response from @adrianreber from [ticket](https://github.com/checkpoint-restore/criu/issues/2185) I created at CRIU repo.

```
The following seems to be the reason for your failure:

(00.214201)   1581: Error (criu/files-reg.c:2094): File var/log/ndb/lst_log/mysqld.n209-035-156.invalid-user.log.WARNING.001 has bad size 378073 (expect 374776)

CRIU stops restoring if any open file has a different file size. Restoring a process with open files that have changed are an indication that something is not right and might result in failures in the future. In you case it could mean that CRIU positions the file pointer at the wrong location during restore and existing data in the log file will be overwritten.

The CRI-O code is based on the Podman code and default behaviour in Podman is that the container does not continue running. In CRI-O and Kubernetes the only possibility is to checkpoint a container and keep it running. From the KEP introducing this into Kubernetes it is the only possibility.

The problem you are now hitting is that your application is checkpointed and then continues running and then we collect in CRI-O all the files that have changed. By the time we collect your files the application has changed the log file and the size we put in the checkpoint archive is now larger. So this is a CRI-O not handling checkpointing process correctly.

CRI-O needs to pause the container before checkpointing and let it continue to run just after all files have been collected.

Should be an easy change. Again, this is a CRI-O problem and not a CRIU problem.
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
root@n209-035-156:~# crio --version
crio version 1.27.0
Version:        1.27.0
GitCommit:      ac97112b9adc9f670506452a02d22d6e43be7d89
GitCommitDate:  2023-05-17T12:33:02Z
GitTreeState:   dirty
BuildDate:      2023-05-18T23:03:23Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  containers_image_ostree_stub
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
root@n209-035-156:~# kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "25+",
    "gitVersion": "v1.25.6-dirty",
    "gitCommit": "ff2c119726cc1f8926fb0585c74b25921e866a28",
    "gitTreeState": "dirty",
    "buildDate": "2023-05-24T23:29:19Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7"
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
root@n209-035-156:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
root@n209-035-156:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@n209-035-156:~# uname -a
Linux n209-035-156 5.4.56.bsk.9-amd64 #5.4.56.bsk.9 SMP Debian 5.4.56.bsk.9 Wed Aug 25 04:08:18 UTC 20 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Physical Server
</details>
[criu.log](https://github.com/cri-o/cri-o/files/11568894/criu.log)

**Comment by adrianreber** [comment]
See #6977 for a possible fix.

**Comment by varungup90** [comment]
Hello @adrianreber I tried to restore my application with your patch, and restore works as expected (no error for file size difference).

I noticed a difference, that post restore for open-source mysql and our customized mysql on restore, mysql process seem to be frozen. I verified, cgroup freezer file, it has value `THAWED`.  `ps aux` lists the process but  I do not see any logs, can not connect to it using mysql cli and it happens with CRIO master branch as well (nothing related to your patch). Just FYI, I will create a separate task for it.

**Comment by adrianreber** [comment]
Thanks for trying it out.

If you see problems without the linked PR then it is indeed something else.

**Comment by MaxFuhrich** [comment]
I'm currently experiencing the same issue when trying to restore a pod for a custom application.
The application is just a Java Spring Controller with two endpoints (one for setting a value of a variable and one for reading it).

Windows Version 10 Pro (10.0.19045)
Virtualbox Version 7.0.8 r156879
Ubuntu Version 22.04.2
Within the Ubuntu VM, I'm using minikube with kubernetes v1.27.3, kubectl v1.27.3 CR-O 1.27, CRIU 3.17.1 (also tried 3.18)

Starting cluster with minikube start --vm-driver=none --container-runtime=crio --feature-gates=ContainerCheckpoint=true
(since im using vm-driver=none im running minikube as root)

I have followed https://martinheinz.dev/blog/85 and https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/ for creating a checkpoint and tried both
approaches for restoring it, including 
enable_criu_support = true
and
drop_infra_ctr = false
in crio.conf.
Creating a checkpoint works fine, analyzing it is also no problem but restoring it isn't possible (or restoring a new cluster or switching to a different vm to try the checkpoint there - I tried some approaches out of desperation).
I get one of the two errors after a few seconds:
The events of the pod for the first error (note that I used an extra container as image registry but used the buildah registry later on):
<details><summary>Events first error</summary>
<p>
Events:

  Type     Reason   Age                 From     Message

  ----     ------   ----                ----     -------

  Normal   Pulled   21m                 kubelet  Successfully pulled image "localhost:5000/checkpoint-image:latest" in 31.599743ms (31.609281ms including waiting)

  Normal   Created  21m                 kubelet  Created container checkpoint-tester-container

  Normal   Started  21m                 kubelet  Started container checkpoint-tester-container

  Warning  Failed   21m                 kubelet  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_checkpoint-tester-container_ganztoll_default_5d14e143-0f1a-4ad4-8efc-21d6de33a9e5_0 for id aa714398c6c465dd13e95ba458aca2fa2621af96b6eb7fcb0bccdc6f5838b94d: name is reserved

  Normal   Pulled   21m                 kubelet  Successfully pulled image "localhost:5000/checkpoint-image:latest" in 25.113957ms (25.12082ms including waiting)

  Normal   Pulled   20m                 kubelet  Successfully pulled image "localhost:5000/checkpoint-image:latest" in 30.700134ms (30.709321ms including waiting)

  Warning  Failed   20m                 kubelet  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_checkpoint-tester-container_ganztoll_default_5d14e143-0f1a-4ad4-8efc-21d6de33a9e5_0 for id a9d7324ee30a5da2db341a4d95358674a8ff4223fe15b491c97eebcff0ea0490: name is reserved

  Normal   Pulled   20m                 kubelet  Successfully pulled image "localhost:5000/checkpoint-image:latest" in 7.913863ms (7.920185ms including waiting)

  Warning  Failed   20m                 kubelet  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_checkpoint-tester-container_ganztoll_default_5d14e143-0f1a-4ad4-8efc-21d6de33a9e5_0 for id 4185b3ae4f08518f6b9da05264264c1444fe34c8dcef95dfb5b2c823fbff3342: name is reserved

  Normal   Pulled   20m                 kubelet  Successfully pulled image "localhost:5000/checkpoint-image:latest" in 15.407035ms (15.415411ms including waiting)

  Warning  Failed   20m                 kubelet  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_checkpoint-tester-container_ganztoll_default_5d14e143-0f1a-4ad4-8efc-21d6de33a9e5_0 for id 648026cac69cc09e681f26010bec115071d97ad0a5ee1d285db7afbd256dc65f: name is reserved

  Normal   Pulled   19m                 kubelet  Successfully pulled image "localhost:5000/checkpoint-image:latest" in 21.653345ms (21.66127ms including waiting)

  Warning  Failed   19m                 kubelet  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_checkpoint-tester-container_ganztoll_default_5d14e143-0f1a-4ad4-8efc-21d6de33a9e5_0 for id a33c43b34e31d24fdf56917efc8e04b227e56b5cac965c691e3137bf5b8aeb08: name is reserved

  Warning  BackOff  19m (x6 over 20m)   kubelet  Back-off restarting failed container checkpoint-tester-container in pod ganztoll_default(5d14e143-0f1a-4ad4-8efc-21d6de33a9e5)

  Normal   Pulling  69s (x76 over 21m)  kubelet  Pulling image "localhost:5000/checkpoint-image:latest"

</p>
</details> 



The events for the second error: 
<details><summary>Events second error</summary>
<p>

Events:

  Type     Reason   Age                    From     Message

  ----     ------   ----                   ----     -------

  Normal   Pulled   6m15s                  kubelet  Successfully pulled image "localhost/newrestore:latest" in 2.188107ms (2.194088ms including waiting)

  Normal   Pulled   6m15s                  kubelet  Successfully pulled image "localhost/newrestore:latest" in 1.44542ms (1.450509ms including waiting)

  Warning  Failed   6m15s                  kubelet  Error: failed to restore container restored-checkpoint-container: container restore failed: time="2023-06-22T16:27:23+02:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log"

  Warning  Failed   6m14s                  kubelet  Error: failed to restore container restored-checkpoint-container: container restore failed: time="2023-06-22T16:27:24+02:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log"

  Normal   Pulled   6m                     kubelet  Successfully pulled image "localhost/newrestore:latest" in 1.774546ms (1.778704ms including waiting)

  Warning  Failed   5m59s                  kubelet  Error: failed to restore container restored-checkpoint-container: container restore failed: time="2023-06-22T16:27:39+02:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log"

  Normal   Pulled   5m58s                  kubelet  Successfully pulled image "localhost/newrestore:latest" in 1.671202ms (1.674829ms including waiting)

  Warning  Failed   5m58s                  kubelet  Error: failed to restore container restored-checkpoint-container: container restore failed: time="2023-06-22T16:27:40+02:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log"

  Normal   Pulled   5m43s                  kubelet  Successfully pulled image "localhost/newrestore:latest" in 3.34233ms (3.34819ms including waiting)

  Warning  Failed   5m42s                  kubelet  Error: failed to restore container restored-checkpoint-container: container restore failed: time="2023-06-22T16:27:56+02:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log"

  Normal   Created  5m41s (x6 over 6m15s)  kubelet  Created container restored-checkpoint-container

  Normal   Pulled   5m41s                  kubelet  Successfully pulled image "localhost/newrestore:latest" in 5.411984ms (5.418225ms including waiting)

  Warning  Failed   5m41s                  kubelet  Error: failed to restore container restored-checkpoint-container: container restore failed: time="2023-06-22T16:27:57+02:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log"

  Normal   Pulling  67s (x35 over 6m15s)   kubelet  Pulling image "localhost/newrestore:latest"

</p>
</details> 
I tried to locate /run/containers/storage/overlay-containers/restored-checkpoint-container/userdata/restore.log but the folder "restored-checkpoint-container" in "storage" didn't exist.

I have also tried #6977 and the approach in #7050 provided by @adrianreber (also using one.yml and restore-one.yml) but with no different outcome.
Since I think this could be the same issue, I'm replying here.
If this is not a bug but a faulty setup (I'm quite new to K8s, CRI-O and CRIU that's why im not sure about my setup, maybe it's an issue because im running as root?) I would appreciate any hints/solutions.
[criolog.txt](https://github.com/cri-o/cri-o/files/11835415/criolog.txt)
[kubeletlog.txt](https://github.com/cri-o/cri-o/files/11835417/kubeletlog.txt)
[checkpoint-testeryaml.txt](https://github.com/cri-o/cri-o/files/11835526/checkpoint-testeryaml.txt)
[restoreyaml.txt](https://github.com/cri-o/cri-o/files/11835529/restoreyaml.txt)

**Comment by adrianreber** [comment]
@MaxFuhrich Not convinced it is useful to add your information here. This seems to be something different.

I need the `restore.log` that you are not able to find. Please create a CRIU configuration file at `/etc/criu/runc.conf` with:
```
log-file /tmp/criu.log
```

**Comment by MaxFuhrich** [comment]
@adrianreber I was able to retrieve the criu logs: 
[criu.log.txt](https://github.com/cri-o/cri-o/files/11835956/criu.log.txt)

**Comment by adrianreber** [comment]
Okay, that is known problem. Not really a problem. But I cannot remember how to fix it. Let me think.

Now I remember. I guess you are trying restore a container into a pod without infrastructure container or the other way around. That cannot work. The pod to restore into must have the same setup concerning the infrastructure container.

**Comment by MaxFuhrich** [comment]
@adrianreber how do I fix this?
I'm not experienced with infrastructure container. Just changed the pause_image to "registry.k8s.io/pause:3.9" in the crio config, hoping that this would help but this gives me the "name reserved" error.
I have attached the new log from criu.
[criu.log.txt](https://github.com/cri-o/cri-o/files/11837223/criu.log.txt)

**Comment by adrianreber** [comment]
@MaxFuhrich Can you try without `drop_infra_ctr = false`? Not sure that that is really helpful.

You can also try to add the following to your pod definition `shareProcessNamespace: true`.

**Comment by MaxFuhrich** [comment]
@adrianreber sadly, this had no effect. After removing `drop_infra_ctr = false` the restore was tried for 5 minutes and then got the name reserved error (see attached files).
`shareProcessNamespace: true` also didn't help and produced the criu error.
[crio.log.txt](https://github.com/cri-o/cri-o/files/11847990/crio.log.txt)
[criu.log.txt](https://github.com/cri-o/cri-o/files/11847992/criu.log.txt)
[events.txt](https://github.com/cri-o/cri-o/files/11847994/events.txt)
[kubelet.log.txt](https://github.com/cri-o/cri-o/files/11847995/kubelet.log.txt)
[shareProcessNamespace.crio.log.txt](https://github.com/cri-o/cri-o/files/11847996/shareProcessNamespace.crio.log.txt)
[shareProcessNamespace.criu.log.txt](https://github.com/cri-o/cri-o/files/11847997/shareProcessNamespace.criu.log.txt)
[shareProcessNamespace.events.txt](https://github.com/cri-o/cri-o/files/11847998/shareProcessNamespace.events.txt)
[shareProcessNamespace.kubelet.log.txt](https://github.com/cri-o/cri-o/files/11847999/shareProcessNamespace.kubelet.log.txt)

**Comment by adrianreber** [comment]
The first criu log files looks like it worked. Please try to reach out on slack and maybe I can help you better there.

**Comment by adrianreber** [comment]
We chatted on slack and the problem was that it was a cgroupv2 system. See https://github.com/cri-o/cri-o/issues/6894

After switching to cgroupv1 everything works.

**Comment by haircommander** [comment]
this is a dup of https://github.com/cri-o/cri-o/issues/6894 so I'm closing
