### ISSUE TITLE
Debian_12 armhf and arm64 packages missing

### ISSUE THREAD

**Issue by grunlab** [cri-o/cri-o#7344]
Hi,

armhf and arm64 packages for Debian_12 are missing: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_12/

While they are available for Debian_11:  https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/

Thank you
Adrien

**Comment by grunlab** [comment]
Up
Thank you

**Comment by kwohlfahrt** [comment]
Not stale - this is still an issue.

**Comment by kwohlfahrt** [comment]
Do I have permission to do this?

/remove-lifecycle stale

**Comment by kwilczynski** [comment]
@kwohlfahrt, most of the bot actions are not locked to owners or contributions only. :smile:

**Comment by haircommander** [comment]
hello all, sorry for the delay, which packages are you looking for? CRI-O, or others in the kubic repo?

**Comment by kwohlfahrt** [comment]
I'm after the following packages: `cri-o`, `cri-o-runc`, and `cri-tools`. It seems there is now an `arm64` folder present in the package repos, and `cri-o` [is present](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27/Debian_12/arm64/). However, the libcontainer packages are still missing `cri-o-runc` and `cri-tools`.

**Comment by haircommander** [comment]
@kwohlfahrt the packages should be ready. @grunlab I may send you to @lsm5 to update those packages as I don't own them

**Comment by lsm5** [comment]
RE: debian 12, IIUC, packages from the official debian experimental repo are usually installable and work fine.

The `kubic:stable` repo has not been updated in years and will not be updated anymore (speaking for everything except cri-o). I recommend you fetch podman, skopeo and buildah from your distro or from some other location. I would have deleted the `kubic:stable` repo entirely but the deletion broke many users so that's why it still exists.  I've added a note in the repo description to reflect current status https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable . You could try your luck with https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable if you got no other convenient option.

**Comment by grunlab** [comment]
Hi,
I've switched from kubic to debian repo for podman, skopeo and buildah installation and all is ok.
Closing the issue.
Thank you
