### ISSUE TITLE
Invalid WorkingSetBytes, AvailableBytes, UsageBytes, RssBytes for RuntimeService.ListContainerStats (RuntimeService.ContainerStats)

### ISSUE THREAD

**Issue by albe19029** [cri-o/cri-o#7354]
### What happened?

Checking implementation for containerd and cadvisor (kubelet) the calculation for WorkingSetBytes, AvailableBytes, UsageBytes, RssBytes working the same:

for cgroups V1:

UsageBytes = memory.usage_in_bytes
RssBytes = memory.stat (total_rss) or (memory.stat (rss)) depending on memory.use_hierarchy is true or false
WorkingSetBytes = memory.usage_in_bytes - memory.stat(total_inactive_file)
AvailableBytes = memory.limit_in_bytes - $WorkingSetBytes

for cgroup V2:

UsageBytes = memory.current
RssBytes = memory.stat (anon)
WorkingSetBytes = memory.current - memory.stat (inactive_file)
AvailableBytes = memory.max - $WorkingSetBytes

So we see that some files and field values were renamed:
memory.usage_in_bytes -> memory.current
memory.limit_in_bytes -> memory.max

And value rss (rss_total) from file  memory.stat was renamed to anon.

But for crio implementation calculation of some of values is strange:

1) the value for UsageBytes is calculating in:

func createMemoryStats(systemNano int64, cgroupStats *libctrcgroups.Stats, cgroupPath string)

and is equal to UsageBytes = cgroupStats.MemoryStats.Usage.Usage. The value for Usage.Usage is calculating in:

func (c *linuxMemHandler) Stat(ctr *CgroupControl, m *cgroups.Stats)

And for me unclear why for  cgroup V1 this value is getting from memory.usage_in_bytes, but for V2 version this value is getting from memory.stat file and "anon" field. anon field don't contains file information and can be used as UsageBytes. Why don't read file memory.current for this?

2) RssBytes value is calculating in:

func UpdateWithMemoryStatsFromFile(memoryStatPath, inactiveFileSearchString string, memory *types.MemoryUsage, usage uint64)

For v1 and V2 they both read rss field. But for V2 this value was renamed to anon. That is why the value of RssBytes is always 0 

3) WorkingSetBytes is calculating in:

func UpdateWithMemoryStatsFromFile(memoryStatPath, inactiveFileSearchString string, memory *types.MemoryUsage, usage uint64)

memory.WorkingSetBytes.Value = usage - totalInactive

But usage now is getting from cgroupStats.MemoryStats.Usage.Usage = memory.stat(anon) for V2. So we extracting file memory from anon memory, which makes no sense as anon memory don't contains file memory. So usage must be the value of memory.current instread

4) AvailableBytes is calculating in:

func createMemoryStats(systemNano int64, cgroupStats *libctrcgroups.Stats, cgroupPath string)

AvailableBytes:  &types.UInt64Value{Value: memUsage - memLimit}

Probably the calculation must be memLimit - memUsage ? As memUsage  is always greater then memUsage.
The second problem is that this value in other implementations is 

AvailableBytes = memLimit - $WorkingSetBytes

Is it possible to fix it, as for crio this values are now totally unusable.

### What did you expect to happen?

expect to work the same as in containerd and cadvisor(kubelet)

### How can we reproduce it (as minimally and precisely as possible)?

can be viewed with crictl stats -o json

### CRI-O and Kubernetes version

all cri-o versions

### OS version

all kernels supporting cgroup v2

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by haircommander** [comment]
cc @Mo-Fatah @sohankunkerkar

**Comment by sohankunkerkar** [comment]
@albe19029 Thanks for raising this issue. There's a PR up to fix the calculation aspect of some of the stats you mentioned. https://github.com/cri-o/cri-o/pull/7514

**Comment by albe19029** [comment]
For now as I see most of the problems still don't fixed. At least RssBytes and AvailableBytes. Is there is a chance that this bug will be fixed?

**Comment by Mo-Fatah** [comment]
this should have been fixed in a recent [PR](https://github.com/cri-o/cri-o/pull/7658). 
Currently, for linux containers, we switched to `libcontainer/cgroups` for metrics gathering : in [cgmgr.ContainrCgroupStats](https://github.com/cri-o/cri-o/blob/main/internal/config/cgmgr/systemd_linux.go#L124-L134) for systemd and [cgmgr.ContainerCgroupStats](https://github.com/cri-o/cri-o/blob/main/internal/config/cgmgr/cgroupfs_linux.go#L95-L105) for cgroupfs. 

both internally call [cgroupMemStats](https://github.com/cri-o/cri-o/blob/main/internal/config/cgmgr/stats_linux.go#L118-L175) which has the values you are asking for. 

### UsageBytes
This is handled by `libcontainer/cgroups`
for cgroupv1: `memory.usage_in_bytes`
for cgroupv2: `memory.current`

### WorkingSetBytes
handled by `cgroupMemStats` https://github.com/cri-o/cri-o/blob/de88477b414c1bd86fa69e11dbefa0b3b98b9099/internal/config/cgmgr/stats_linux.go#L147-L154
This is how cAdvisor calculates it.

### AvailableBytes
handled by `cgroupMemStats` https://github.com/cri-o/cri-o/blob/de88477b414c1bd86fa69e11dbefa0b3b98b9099/internal/config/cgmgr/stats_linux.go#L155-L158

### RssBytes
handled by `cgroupMemStats`
for cgroupv1: RssBytes = memory.stat (total_rss)
https://github.com/cri-o/cri-o/blob/de88477b414c1bd86fa69e11dbefa0b3b98b9099/internal/config/cgmgr/stats_linux.go#L143
for cgroupv2: RssBytes = memory.stat (anon)
https://github.com/cri-o/cri-o/blob/de88477b414c1bd86fa69e11dbefa0b3b98b9099/internal/config/cgmgr/stats_linux.go#L133

Can you check again and see ? probably you should switch to master upstream because these changes aren't included in the latest release.
