### ISSUE TITLE
configurable minimum memory limit

### ISSUE THREAD

**Issue by haircommander** [cri-o/cri-o#7694]
currently, the memory limit for a container is hardcoded to be 15mb minimum. This is mostly for runc, who needs (sometimes more than) that to start. however, this doesn't apply to all OCI runtimes, and it should be a configurable option for the runtime handler

**Comment by d4v1d03** [comment]
@haircommander can you assign this issue to me ...also could you please elaborate a bit more on the same

**Comment by kwilczynski** [comment]
> @haircommander can you assign this issue to me ...also could you please elaborate a bit more on the same

@d4v1d03 not sure if you noticed, this is already assigned.

**Comment by kwilczynski** [comment]
@d4v1d03, that said... if you really think this is something you'd want to work on, then I can assign it to you.

This is something we've discussed internally, so I am happy to help fill in the gaps here if you want.

**Comment by d4v1d03** [comment]
@kwilczynski yes please i'd like to work on but i might need more info on the "internal discussion" part you mentioned...that might save me some time

**Comment by kwilczynski** [comment]
@d4v1d03, it's all yours!

I will add a little bit more details here for you to fill some gaps in a moment.

**Comment by kwilczynski** [comment]
@d4v1d03, how well do you know how CRI-O works or its architecture?

I would imagine you are contributing first time. So, if you need a refresher of how things work internally, a very brief one, then have a look at the following, these might help:

- [CRI-O](https://cri-o.io/)
- [Introduction to CRI-O](https://www.youtube.com/watch?v=V53nSS2mnsM)
- [CRI-O: Under the Hood ](https://www.youtube.com/watch?v=3kz-pERV6Qg)

Also, about containers, should you need a more deep-dive refresher:

- [Demystifying Containers – Part I: Kernel Space](https://www.suse.com/c/demystifying-containers-part-i-kernel-space/)
- [Demystifying Containers – Part II: Container Runtimes](https://www.suse.com/c/demystifying-containers-part-ii-container-runtimes/)
- [Demystifying Containers – Part III: Container Images](https://www.suse.com/c/demystifying-containers-part-iii-container-images/)
- [Demystifying Containers – Part IV: Container Security](https://www.suse.com/c/demystifying-containers-part-iv-container-security/)

**Comment by kwilczynski** [comment]
@d4v1d03, the aim here is to reduce the initial memory footprint required when CRI-O (the CRI) starts a given runtime (so-called OCI) such as **runc** or **crun**. Even though CRI-O supports so-called [Kata Containers](https://katacontainers.io/), these work differently and are out of scope.

When CRI-O starts a container, one of the steps involved in the entire process of doing so, would be to set up a cgroups (which can be v1 or v2 type) for a given container and set a variety of things in advance, such as the memory CPU limit, memory limit, etc.

Typically, a container or Kubernetes Pod (which can contain one or more containers), would have some limits set in advance according to the need of the process running within the container. Thus, most users and most workloads running within containers wouldn't necessarily notice anything.

That said, CRI-O aims to ensure that a given OCI, such as the runc, has enough resources (the very bare minimum) initially to start. This minimum limit is currently hardcoded to be 12 MiB on the x86_64 platform. This limit was initially put in place only for runc, but since it's hardcoded and the code base makes currently no effort to distinguish between different OCI types, and as such, a much smaller (in terms of resource usage footprint) runtime such as crun will also have the same minimal limit set—this is wasteful and would also stop users from running containers that require very few resources to start.

Note that this is only affecting the initial memory usage and will not limit future container memory usage in any way.

The relevant code can be found as follows:

https://github.com/cri-o/cri-o/blob/91816d7e8a38df2c307811f80d2e34fb53f01a21/internal/config/cgmgr/cgmgr_linux.go#L22-L41

https://github.com/cri-o/cri-o/blob/91816d7e8a38df2c307811f80d2e34fb53f01a21/internal/config/cgmgr/cgmgr_linux.go#L152-L157

https://github.com/cri-o/cri-o/blob/91816d7e8a38df2c307811f80d2e34fb53f01a21/internal/config/cgmgr/cgmgr_linux.go#L125-L149

Have a look, and let me know if there is anything unclear at this point. :smile:

**Comment by kwilczynski** [comment]
@d4v1d03, we now know _what_ we need and _why_, and so we can focus on _how_.

Few things to consider here:

- We need to have a way to look up safe (or sane, if you wish) default values for a different OCI runtime
- We need to allow users to override the default value for a given runtime (such as runc, crun, etc.)
- (Optionally) We could allow users to override the default value for every OCI runtime (globally)

Each of the above can be implemented as an addition to CRI-O configuration file handling, such that new settings are added in the right places. Only the optional item of the above list could also use a command-line switch and an environment variable (remains to be seen) for the user to set the desired global value.

So, have a look at CRI-O's configuration file, which uses TOML format and already has a way to provide OCI runtime-specific and global settings and overrides. You can find examples as follows:

- [cri-o/cri-o/docs/crio.8.md](https://github.com/cri-o/cri-o/blob/main/docs/crio.8.md)
- [cri-o/cri-o/docs/crio.conf.5.md](https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md)

You can also generate the current configuration file using the CRI-O binary itself via the `crio config` command.

For the configuration file, pay special attention to the notion of different "tables" that TOML supports.

Let me know if anything is unclear at this point. :smile:

**Comment by d4v1d03** [comment]
Hey @kwilczynski , I'm really sorry i didn't keep in my that my university exams were about to start. It's ok you can go for it, i would need a week or more. I apologize again for the delay due to me.

**Comment by kwilczynski** [comment]
@d4v1d03, good to hear from you!

Not to worry. I wasn't simply sure if you were still interested or got stuck, needed help, etc.

Let's do this: finish your exams, and don't worry about this for now. I will keep it for you.

Also... good luck! I wish you at most success with your exams!

/assign d4v1d03

**Comment by kwilczynski** [comment]
Here are a few tips for the future.

To get the human-friendly memory values such as "10m" or "768K" turned into proper bytes values, you can use something that CRI-O already uses (it won't be a new import, that is), an example:

```go
bytes, err := units.RAMInBytes(aStringValue)
fmt.Println(bytes, err)
``` 

The biggest challenge of this task will most likely be to figure out what to do with the two utility functions:

```go
VerifyMemoryIsEnough(int64) error 
```

```go
verifyCgroupHasEnoughMemory(string, string, string) error 
```

The bottom one relies on the other, and it's also private to the package. As such, there is no straightforward way to wire in the `RuntimeConfig` type for them to use (there is a gotcha here: `config` package imports `cgmgr` package).

**Comment by prakrit55** [comment]
hey @kwilczynski, I had a query, could there be a way to make two of it
`func VerifyMemoryIsEnough(memoryLimit int64) error { `  
one for other OCIs and the runc could have the current one? WDYT

**Comment by kwilczynski** [comment]
@prakrit55, can you give me an example of what you had in mind? Why separate functions?

**Comment by prakrit55** [comment]
ohh, my bad😥 I assumed it as `minMemoryLimit < memoryLimit`

**Comment by kwilczynski** [comment]
@d4v1d03, just checking whether you are still interested in working on this?

**Comment by d4v1d03** [comment]
Yes @kwilczynski , i am going through the content in https://github.com/cri-o/cri-o/issues/7694#issuecomment-1906523045 you had sent. Will update you soon with what conclusion i got over the issue.

**Comment by kwilczynski** [comment]
@d4v1d03, very nice!

Feel free to contact me or other maintainers on the `#crio` Slack channel on the Kubernetes Slack community.

To give you something to think about (in no particular order):

1. You need a way to accept a command-line (CLI) argument to CRI-O on startup
2. You need a way to pass a desired value via the CRI-O configuration file (two places where this needs to be done)
4. You then need a small helper that would allow you to resolve value from the configuration file (CLI vs configuration file)
5. You need to pass this final value, the final memory limit in bytes, to the function that does the validation

Let me know if you have questions.

**Comment by roman-kiselenko** [comment]
I would like to work on this 🙏

**Comment by kwilczynski** [comment]
@roman-kiselenko, thank you!
/assign roman-kiselenko

**Comment by kwilczynski** [comment]
@roman-kiselenko, I hope that I left enough details about this feature to follow. :smile:

**Comment by roman-kiselenko** [comment]
@kwilczynski yep, thx, it's pretty clean, I'll give it a try.
