### ISSUE TITLE
"Fix CVE-2024-3154" shows up in release notes for v1.29.5 and v1.29.4

### ISSUE THREAD

**Issue by buckaroogeek** [cri-o/cri-o#8249]
Just wanted to check if the release notes for v1.29.5 were accurate announcing a fix for CVE-2023-3154? 

thanks

Brad

**Comment by kwilczynski** [comment]
@buckaroogeek, the CVE you linked points against some WordPress related one.

Did you have the following one in mind?

- https://github.com/cri-o/cri-o/security/advisories/GHSA-2cgq-h8xw-2v5j

If so, then I believe it has been addressed in the latest releases. @haircommander can keep me honest here, though.

**Comment by buckaroogeek** [comment]
Apologies for getting the text wrong. The title was correct. The text in the message. It should have been "CVE-2024-3154"

**Comment by haircommander** [comment]
very weird, yeah it was fixed in 1.29.4 (but the fix is also in 1.29.5 :) ) I'm not sure why the release notes automation did that

**Comment by haircommander** [comment]
what's weirder is it was supposed to have info about CVE-2024-5154 but didn't. I've manually changed the release notes on github

**Comment by kwilczynski** [comment]
@haircommander oh my! Thank you for fixing it! I got confused, slightly too. :smile: 

@buckaroogeek, thank you for getting in touch about this and pointing out the mishap. Appreciated.

**Comment by buckaroogeek** [comment]
I might also note that this error also shows up in the 1.28.7 changelog.

**Comment by saschagrunert** [comment]
Hm, that's the run for v1.28.7 https://github.com/cri-o/cri-o/actions/runs/9334178459/job/25719699456.

We start at v1.28.6, which is on 77bbb1c279801c7d5c88b39281e22c033ccde362. The PR for that merge commit will be included in the notes, means https://github.com/cri-o/cri-o/pull/8086 which mentions the CVE fix. 

Usually, including the previous tag should be no problem, because it's mainly referring to a version bump without any release note. In the case above, we fiddled it together with the CVE fix. So we can either:

- Don't add user facing changes into the version bumps (the default with the new automation)
- Or change the release notes script to use the start rev + 1 commit.

**Comment by haircommander** [comment]
yeah I agree start+1 probably is most correct

**Comment by haircommander** [comment]
though it's not typical for the release bump PR to be tied to the change. we could also just not do that

**Comment by saschagrunert** [comment]
> yeah I agree start+1 probably is most correct

Proposing that in https://github.com/kubernetes-sigs/release-sdk/pull/354, will take a bit until it's part of the `release-notes` tool.
