### ISSUE TITLE
 Error building CRI-O locally using make

### ISSUE THREAD

**Issue by seifrajhi** [cri-o/cri-o#8571]
### What happened?

Hello, 
I encountered errors while trying to build CRI-O following the [installation documentation](https://github.com/cri-o/cri-o/blob/main/install.md). The errors are related to the Go version specified in the `go.mod` file and an unknown directive.

```
ubuntu $ make
go build -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/version.buildDate='2024-09-08T08:03:37Z' ' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion   selinux  exclude_graphdriver_devicemapper" -o bin/crio ./cmd/crio
go: errors parsing go.mod:
/root/cri-o/go.mod:1: invalid go version '1.22.0': must match format 1.23
/root/cri-o/go.mod:3: unknown directive: toolchain
make: *** [Makefile:219: bin/crio] Error 1
```

### What did you expect to happen?

 I expected the make command to successfully build CRI-O without any errors.

### How can we reproduce it (as minimally and precisely as possible)?

1. Clone the CRI-O repository:
   ```sh
   git clone https://github.com/cri-o/cri-o
   cd cri-o
   ```
2. Run `make`:
   ```sh
   make
   ```
   
 **Error Output**:
```
go build -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/version.buildDate='2024-09-08T07:55:11Z' ' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion   selinux  exclude_graphdriver_devicemapper" -o bin/crio ./cmd/crio
go: errors parsing go.mod:
/root/cri-o/go.mod:1: invalid go version '1.22.0': must match format 1.23
/root/cri-o/go.mod:3: unknown directive: toolchain
make: *** [Makefile:219: bin/crio] Error 1
```

### Anything else we need to know?

I also tried using [packages](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/), but the latest version available is 1.28, and I need version 1.30.

### CRI-O and Kubernetes version

N/A, as I am trying to install CRI-O as runtime for my k8s cluster

### OS version

**System Information**:
- OS: Ubuntu 20.04.5 LTS (Focal Fossa)
- Kernel: 5.4.0-131-generic
- Make version: 4.2.1
- Go version: go1.18 linux/amd64

### Additional environment details (AWS, VirtualBox, physical, etc.)

Virtual machine

**Comment by kwilczynski** [comment]
@seifrajhi, your Go version is too old and does not support the `toolchain` directive added to the `go.mod` file.

This is not a CRI-O issue but a build environment one.

Starting with Go 1.21 or newer, the `toolchain` directive adds new functionality and restrictions on Go version, see:

- Go 1.21 Release Notes / [Tools](https://go.dev/doc/go1.21#tools)
- [Go Toolchains](https://go.dev/doc/toolchain)

You can try to remove the `toolchain` directive from the `go.mod` file, and see if this helps. You also need to fix the version format that the older version of Go expects, and this will also cause problems.

However, the **Go 1.18** is quite old and most likely some packages won't build with it anyway. I also don't recommend building CRI-O with such an old version, as you will bring over all the bugs and security vulnerabilities that have since been fixed.

If you have to build on such an old platform, see if something like the following project could help you deploy a more modern version of Go locally so you can build CRI-O with it:

- [gobrew](https://github.com/kevincobain2000/gobrew): Go version manager, written in Go.

**Comment by seifrajhi** [comment]
Following your comment, I just ran `rm -rf /usr/local/go` on Ubuntu then reinstalled latest version
```
ubuntu $ go version
go version go1.23.1 linux/amd64
```

I manged to run make successfully after of course adding the packages like seccomp etc,

Thank you @kwilczynski, closing this issue.
